### ISSUE TITLE
ivy parsing: new_symbol rule not handled

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#222]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 10, 2013 13:27:42_

In the CLI enter:

scala> loadProver9Proof( "../testing/prover9-TSTP/ALG/ALG353-1/Prover9---1109a.UNS-Ref.s.out" )

Instead of loading a proof an exception is thrown. The problem seems to be in parsing paramodulation rules. This is one of the bugs that appears most often in the ALG-part of the prover9-TSTP, it seems to be the cause of the failures of: ALG138+1, ALG007-1, ALG111+1, ALG113+1, ALG337-1,...

_Original issue: http://code.google.com/p/gapt/issues/detail?id=222_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 10, 2013 07:02:48_

The source seems to be an undocumented rule for symbol introduction, the lines in prover9's output look like this:

    32 complement(converse(sk1)) = c_0.  [new_symbol(30)].

They can be simulated by adding this into the set of initial clauses. When we extract the end-sequent, we have to add them to keep the formula valid.

**Summary:** ivy parsing: new_symbol rule not handled  \<span class="oldvalue"> (was: ivy parsing: paramodulation) \</span>  
**Status:** Accepted

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2013 11:30:27_

**Blocking:** gapt:228

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on January 19, 2013 11:32:15_

**Status:** Started  
**Owner:** Martin.R...@googlemail.com  
**Cc:** -Martin.R...@googlemail.com stefan.hetzl

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on July 03, 2013 01:43:38_

As of revision 1601 the status of the files mentioned above is the following:
ALG353-1 OK
ALG138+1 OK
ALG007-1 failure at name_replacement.scala:232
ALG111+1 OK
ALG113+1 OK
ALG337-1 OK

**Comment by shetzl** [comment]
adding CCs from google code: @shetzl @quicquid

**Comment by shetzl** [comment]
As a sweep over the regression test suite for prover9-import indicates, this bug seems to be the most frequent cause for failure. It shows up in form of an exception "Could not find a match for element ... in List ..." thrown in name_replacement:280 (used to be 232 in r1601) where the first ... contains a symbol like c_0,c_1,... which are introduced by prover9 using the above-mentioned undocumented "new_symbol"-rule.

This bug still occurs, for example, in

loadProver9Proof( "testing/TSTP/prover9/ALG/ALG007-1/Prover9---1109a.UNS-Ref.s.out" )
loadProver9Proof( "testing/TSTP/prover9/REL/REL005-3/Prover9---1109a.UNS-Ref.s.out" )
loadProver9Proof( "testing/TSTP/prover9/REL/REL050-4/Prover9---1109a.UNS-Ref.s.out" )
loadProver9Proof( "testing/TSTP/prover9/GRP/GRP072-1/Prover9---1109a.UNS-Ref.s.out" )
loadProver9Proof( "testing/TSTP/prover9/HEN/HEN006-5/Prover9---1109a.UNS-Ref.s.out" )
loadProver9Proof( "testing/TSTP/prover9/LCL/LCL548+1/Prover9---1109a.THM-Ref.s.out" )
loadProver9Proof( "testing/TSTP/prover9/MGT/MGT048-1/Prover9---1109a.UNS-Ref.s.out" )

@frehn adding Daniel to CCs

**Comment by quicquid** [comment]
Hi Stefan,

I did some debugging and found the problem, but i don't have a good solution. What I can do is to describe what is going on:

Prover 9 has an ondocumented rule called new symbol, which replaces a subterm by a constant. When we import a proof, we remove this constant by rewriting it to the original term. The error message occurs because the algorithm cannot find the rewritten auxiliary literal in the parent caluse.

Let's take ALG007-1 as an example which contains the following inferences:

17 difference(A,A) = difference(B,B).  [para(10(a,1),2(a,1,2)),rewrite([15(6),8(6)])].
23 difference(A,A) = c_0.  [new_symbol(17)].
24 difference(A,c_0) = A.  [para(23(a,1),1(a,1,2))].

In this case, the rewrite rule to be applied is for c_0 -> difference(B,B) . Now the free variable B creates the problem, since it is unclear, which term needs to be inserted after rewriting.

During execution the variables are renamed, resulting in the rewrite rule c_0 -> difference(B,B). When the instantiation rule with the substitution v0 -> v100 is applied to the clause =(difference(v0, v0), c_0), we get =(difference(v100, v100), c_0) which rewrites to =(difference(v100,v100),difference(v0,v0)). But the proof of the parent without the new_symbol rule has the clause =(difference(v0, v0), difference(v0, v0)), which is =(difference(v100, v100), difference(v100, v100)) after substitution.

I will now enumerate the solutions i thought of and explain why they won't work:
a) adjust the rewrite rule by applying the substitution: the clause might be used twice with different (incompatible) substitutions
b) apply the current substitution to the rewrite rule, but don't adjust it: then subsequent substitions on the same term will  not work.

I implemented approach b) in the branch newsymbol which fixed 4 out of the 7 examples above. Can you test, if there are no regressions with it? Then we can leave it in and have at least some remedy.

**Comment by shetzl** [comment]
It looks to me as if the correct solution would be to apply the instantation rule not to the clause
=(difference(v0, v0), c_0)
but instead to the clause where c_0 is already replaced, i.e.:
=(difference(v0, v0), difference(v0, v0))

In other words, it looks as if elimination the new symbols _before_ subjecting the clause to substitutions is the correct solution. Would that be possible?

**Comment by gebner** [comment]
It seems that prover9 uses the new_symbol rule in at least two ways

1. Abbreviate a ground term by a constant.  In this case, the parent proof node does not seem to matter; anyways, we can always replace this constant.
2. If prover9 can prove that a function is constant (in some way), e.g. difference(A,A) = difference(B,B), then it will introduce a constant symbol for this constant value.  In this case, the parent proof node is important, because it gives a justification why the function is constant and can be abbreviated.

Commit da05b2512e0492914cdc8c32f0e6fccc2ed01b2f handles the second case explicitly, first replacing the new_symbol constant by the replacement term with fresh variables (i.e. difference(B000, B000)), and then replacing the initial clause difference(A,A)=difference(B000,B000) with the proof prover9 gives as a justification.
