### ISSUE TITLE
Tactics-based proof input

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#241]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on May 22, 2013 18:22:56_

In the long run, the hlk-implementations (including shlk) should be superseded by an LCF-style tactic-language for proof formalization. In the following I am describing how such a language could be integrated into GAPT.

The basic setting is that of bottom-up construction of a sequent calculus proof.

A "goal" is just a sequent (marked as goal). A "proof segment" is a proof starting from axioms and goals. A "proof state" consists of (a suitable representation (see below) of) a proof segment and one goal designated as the "current goal"

The CLI should be enhanced as follows:

* Add a global variable "curpstate" for the current proof state.

* Add a command "theorem" of type HOLFormula -> unit which initializes the curpstate with the proof state consisting of the formula as the only goal.

* Add a command "apply" of type "tactic -> unit" where tactic is defined as "goal -> list(goal) x proof_segment". This command modifies curpstate by applying the given tactic to the current goal. This application is done by justifying the current goal from the obtained list of goals and the obtained proof segment.

* Add a command "qed" of type "unit -> LKProof" which creates an actual LKProof from the proof segment contained in curpstate.

Something worth considering for the proof state is to keep the internal structure of the proof segment in smaller proof segments to permit more flexibility, e.g. an undo-function.

Both theorem and apply should print the list of currently open goals (or at least the current goal).

Basic tactics that should be implemented include all sequent calculus rules (bottom-up constructors).

More advanced tactics that should be implemented include the tableaux-prover "autoprop".

Many tactics will need additional arguments, like e.g. which formula in a sequent it should be applied to. A solution of this is to number formulas in the sequent and have the tactic expect the number of the formula.

Example session for the sake of illustration (don't take this too literally):

\> theorem( "(Impl (And A B) A)" )

goal:
  |- (Impl (And A B) A)

\> apply( impl_r )

goal:
  (And A B) |- A

\> apply( and_l1 )

goal:
  A |- A

\> apply( axiom )

no more goals.

\> qed
res12: at.logic.calculi.lk.base.LKProof = ...

Every such proof-script is a scala script and can be loaded into the CLI with the scala :load-command.

This approach has the following advantages:
* Bottom-up proof construction (which is necessary for larger proofs, top-down does not work well)
* It largely avoids the necessity of entering formulas - this only needs to be done at the very beginning of a proof and for non-analytic rules.
* It is extremely easy to extend. Any scala function of type tactic is an applicable tactic.

It has the following disadvantage:
* For a human to understand a proof-script it needs to be run, reading it will typically not be enough.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=241_

**Comment by newca12** [comment]
_From [Martin.R...@googlemail.com](https://code.google.com/u/113922991942493634983/) on June 07, 2013 08:09:45_

**Cc:** Martin.R...@googlemail.com shaoli...@gmail.com cdunc...@gmail.com cernadav...@gmail.com

**Comment by shetzl** [comment]
adding CCs from google code: @shaolintl @shetzl @quicquid

**Comment by gebner** [comment]
I have experimented a bit, see https://github.com/gebner/gapt/tree/tactics in particular https://github.com/gebner/gapt/blob/ac57c8c39dc8a499fedd18eb86a8a916d5e57a69/src/main/scala/at/logic/gapt/provers/tactics/tactics.scala#L68 (ignore the monad stuff, this doesn't work yet.)

You can then construct proofs like this:
```scala
val n = 4

val es =
  ( "f(0) = s(0)" +: "f(s(x)) = s(x)*f(x)" +:
    "g(x,0) = x" +: "g(x,s(y)) = g(x*s(y),y)" +:
    "x*s(0) = x" +: "s(0)*x = x" +:
    "(x*y)*z = x*(y*z)" +:
    Sequent()
    :+ "g(s(0), xn) = f(xn)"

    map parseFormula
    map ( univclosure( _ ), FOLSubstitution( FOLVar( "xn" ) -> Utils.numeral( n ) ).apply ) )

val p = new TacticsProver( es ) {
  rewrite( "a1", in = "b0" )
  repeat {
    rewrite( "a1", in = "b0" )
    rewrite( "a6", in = "b0", flip = true )
  }
  rewrite( "a0", in = "b0" )
  rewrite( "a4", in = "b0" )
  repeat { rewrite( "a3", in = "b0" ) }
  rewrite( "a2", in = "b0" )
  rewrite( "a5", in = "b0" )
  refl
}.constructProof
```

(This proves the equality of head-recursive and tail-recursive factorials for a fixed numeral argument `n`.)

There are also propositional `cases`, `elim`, and `apply` tactics.  And a `prover9` tactic if you're lazy. :smile:

Thoughts:
* You need to specify which formula you want to work with in every single tactic.  Maybe focusing would be a better aproach?
* I have used strings to label formulas instead of sequent indices because strings do not change when you apply tactics as indices would.  The labels could however be better--should you provide them when you want to prove a theorem?  Maybe name them after the root symbol in the formula they label?  Explicitly tell the cut tactic which label to use?
* The proof state is mutable, and failure of a tactic is indicated by throwing an exception.  Repeat tries the tactics until an exception is thrown... I really don't like this.
* The UI story is a bit non-existent.  I constructed the proofs by writing code like the following:
```scala
new TacticsProver(endSequent) {
  // some tactics
  printState
}
```
and then repeatedly executing the file.  Maybe scala worksheets in intellij would provide a nicer interface?

**Comment by gebner** [comment]
I just found out about a similar project from Chalmers: [PESCA, a proof editor for sequent calculus](http://www.cs.helsinki.fi/u/hakli/proof_theory/2002/proof_theory/manual.pdf).

Weirdly enough, they focus formulas in a sequent, but not subgoals in a proof.  Instead, you have to enter the position of the current goal each time you want to apply a rule.

Another interesting design choice is that they number formulas in the succedent beginning from the right, i.e. in the sequent `a,b,c:-d,e,f,g` the formula `g` has index `S 1`.

This is actually the *only* tactics-like prover for a sequent calculus that I know of.  All the well-known proof assistants use natural deduction as far as I am aware.

**Comment by gebner** [comment]
ccing @alexanderbirch so that you also get notified!

I have been thinking a bit about the way tactic proofs will be used in the end.  I have also been experimenting with a proof about partial orders lately; so obviously I imagined how to write that proof using tactics:

```scala
package at.logic.gapt.examples
import at.logic.gapt.expr._
import at.logic.gapt.proofs.gaptic._

object PosetExample {

  private val f = FOLFunctionHead("f", 2)
  private val Seq(u, v, w, x, y, z) = Seq("u", "v", "w", "x", "y", "z") map { FOLVar(_) }
  private val Seq(a, b, c) = Seq("a", "b", "c") map { FOLConst(_) }

  val cycleImpliesEqual =
    Lemma(
      ("eqrefl" -> All(x, x === x)) +:
      ("eqsymm" -> All(x, All(y, (x === y) --> (y === x)))) +:
      ("eqtrans" -> All(x, All(y, All(z, ((x === y) & (y === z)) --> (x === z))))) +:
      ("eqfcongr" -> All(x, All(y, All(u, All(v, ((x===y) & (u===v)) --> (f(x,u) === f(y,v))))))) +:
      ("fcomm" -> All(x, All(y, f(x, y) === f(y, x)))) +:
      ("fassoc" -> All(x, All(y, All(z, f(f(x, y), z) === f(x, f(y, z)))))) +:
      Sequent()
      :+ ("goal" -> ((f(a, b) === a) & (f(b, c) === b) & (f(c, a) === c)) --> ((a === b) & (b === c)))
    )(
      cut("cf",
        All(x, All(y, All(z, ((f(x, y) === x) & (f(y, z) === y)) --> (f(x, z) === x))))
        & All(u, All(v, ((f(u, v) === u) & (f(v, u) === v)) --> (u === v)))),

      forget("goal"),
      destruct("cf") then intros(),

      // transitivity
      apply("eqtrans").subst(y -> f(f(x,y),z)), destruct("cf"),
      apply("eqsymm"), apply("eqfcongr"), destruct("cf"), apply("eqrefl"), prop(),
      apply("eqtrans").subst(y -> f(x,f(y,z))), destruct("cf"),
      apply("fcomm"),
      apply("eqtrans").subst(y -> f(x,y)), destruct("cf"),
      apply("eqfcongr"), destruct("cf"), apply("eqrefl"), prop(),
      prop(),

      // anti-symmetry
      apply("eqtrans").subst(y -> f(u,v)), destruct("cf"),
      apply("eqsymm"), prop(),
      apply("eqtrans").subst(y -> f(v,u)), destruct("cf"),
      apply("fcomm"),
      prop(),

      // right side of the cut
      intros(), destruct("cf"), destruct("goal"),

      // a=b
      apply("cf_2"), destruct("goal"),
        // f(a,b)=a
        prop(),
        // f(b,a)=b
        apply("cf_1").subst(y -> c), destruct("goal") then prop(),

      // b=c
      apply("cf_2"), destruct("goal"),
        // f(b,c)=b
        prop(),
        // f(c,b)=c
        apply("cf_1").subst(y -> a), destruct("goal") then prop(),

      qed
    )

}
```

The details of the proof are not really important.  I'm posting this as a starting point for discussion about how the tactics language could look like given the current idea on how the data structures should look like.

Notable points:
* There is not even one (explicit) use of a "or-right" or "imp-left" tactic, most of the work happens using an automatically `apply` tactic, which takes a formula like `forall x, a -> p(x)` in the antecedent and "applies" it to a formula `p(c)` in the succedent.
* At least in this example, it seems like a good idea to operate on the formula in the succedent by default if the user doesn't specify anything else.
* The labels are really nice to use.
* Debugging this proof would be quite a pain, passing the tactics as a list means that you can't use a debugger to single step through the proof, or run until a breakpoint.  Making the tactics prover mutable might help, but then we lose the ability to modify and combine tactics--see the `.subst(...)` method and `then` combinator in the example.
* This is probably the most controversial point: I firmly believe that the same principles that apply to software development also apply to the formalization of proofs.  Formalized proofs need to be compiled, automatically, otherwise they silently stop working because of changes in the syntax of the tactics.  They need to be executed and tested as well, otherwise they stop working because of changes in the semantics.  They need to be documented, otherwise the unlucky ones who need to maintain the proofs have little chance of fixing them.  For this reason I intentionally put the proof in an object inside a package, intended to be automatically compiled by a build system like sbt.  I envision that if anybody external wants to do a large formalization in gapt, they will set up an sbt project and add gapt as a dependency.  (This is much less boilerplate than you might think.)

BTW, the last point is not a joke.  I remember a talk at last year's Coq workshop from the ssreflect guys who had a continuous integration server just to make sure their formalization still builds.  Proofs are code, not just on a deep theoretical level.

**Comment by quicquid** [comment]
I strongly agree to the last point. From time to time, there are questions about the conversion of old Isabelle proof scripts on the isabelle-users mailing list and it appears to be pretty painful, if a proof has not been maintained for a few years. In the case of Isabelle, the [archive of formal proofs](http://afp.sourceforge.net) hosts the library against which each release is tested.

**Comment by quicquid** [comment]
Regarding debugging: I think only the simplest proof scripts can be understood without the current context of open obligations. I see two approaches there: either a dedicated UI parses the proof or the proof script can be written back to a file which has the obligations in the comments.

**Comment by gebner** [comment]
I just found an interesting master thesis from 1986 by a student of Dale Miller: [Using Extended Tactics to Do Proof Transformations](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.473.9630)

They present a tactics language for LK, however it feels a bit bare-bones and fails to address important issues such as how name formulas, and they do not even include an example of a proof using their language.  On the positive side they have a nice implementation of a propositional prover as `repeat(... orElse ... orElse ...)`.

But then there's also some stuff about importing resolution proofs to LK via expansion trees. :smile: And the tactics prover also seems to be able to prove expansion trees instead of sequents--I'm really not sure what the intended use case for that feature is.

**Comment by gebner** [comment]
As promised, I've reworked the example to use an imperative tactics prover where you can put breakpoints in the proof:
```scala
package at.logic.gapt.examples
import at.logic.gapt.expr._
import at.logic.gapt.proofs.gaptic._

object PosetExample {

  private val f = FOLFunctionHead("f", 2)
  private val Seq(u, v, w, x, y, z) = Seq("u", "v", "w", "x", "y", "z") map { FOLVar(_) }
  private val Seq(a, b, c) = Seq("a", "b", "c") map { FOLConst(_) }

  val cycleImpliesEqual =
    new Lemma(
      ("eqrefl" -> All(x, x === x)) +:
      ("eqsymm" -> All(x, All(y, (x === y) --> (y === x)))) +:
      ("eqtrans" -> All(x, All(y, All(z, ((x === y) & (y === z)) --> (x === z))))) +:
      ("eqfcongr" -> All(x, All(y, All(u, All(v, ((x===y) & (u===v)) --> (f(x,u) === f(y,v))))))) +:
      ("fcomm" -> All(x, All(y, f(x, y) === f(y, x)))) +:
      ("fassoc" -> All(x, All(y, All(z, f(f(x, y), z) === f(x, f(y, z)))))) +:
      Sequent()
      :+ ("goal" -> ((f(a, b) === a) & (f(b, c) === b) & (f(c, a) === c)) --> ((a === b) & (b === c)))
    ) {
      use(cut("cf",
        All(x, All(y, All(z, ((f(x, y) === x) & (f(y, z) === y)) --> (f(x, z) === x))))
        & All(u, All(v, ((f(u, v) === u) & (f(v, u) === v)) --> (u === v)))))

      use(forget("goal"))
      use(destruct("cf") onAll intros())

      // transitivity
      use(apply("eqtrans").subst(y -> f(f(x,y),z))); use(destruct("cf"))
      use(apply("eqsymm")); use(apply("eqfcongr")); use(destruct("cf")); use(apply("eqrefl")); use(prop())
      use(apply("eqtrans").subst(y -> f(x,f(y,z))); use(destruct("cf"))
      use(apply("fcomm"))
      use(apply("eqtrans").subst(y -> f(x,y))); use(destruct("cf"))
      use(apply("eqfcongr")); use(destruct("cf")); use(apply("eqrefl")); use(prop())
      use(prop())

      // anti-symmetry
      use(apply("eqtrans").subst(y -> f(u,v))); use(destruct("cf"))
      use(apply("eqsymm")); use(prop())
      use(apply("eqtrans").subst(y -> f(v,u))); use(destruct("cf"))
      use(apply("fcomm"))
      use(prop())

      // right side of the cut
      use(intros()); use(destruct("cf")); 
      use(destruct("goal") onAll (apply("cf_2") then destruct("goal") then prop()));

      // f(b,a)=b
      use(apply("cf_1").subst(y -> c)); use(destruct("goal") onAll prop())

      // f(c,b)=c
      use(apply("cf_1").subst(y -> a)); use(destruct("goal") onAll prop())

    } qed

}
```

* The `then` tactic now does something different: `then` just performs the tactics in sequence, `onAll` applies a tactic to all new subgoals.
* If we can the macro syntax working, then it might even be possible to single step inside compound tactics, i.e. inside on onAll for example.

**Comment by shetzl** [comment]
As discussed in yesterday's gapt meeting, in the above script "apply" should be replaced by "chain" and "intros" should be replaced by "decompose".

**Comment by gebner** [comment]
Here's the updated draft:
```scala
package at.logic.gapt.examples
import at.logic.gapt.expr._
import at.logic.gapt.proofs.gaptic._

object PosetExample {

  private val f = FOLFunctionHead("f", 2)
  private val Seq(u, v, w, x, y, z) = Seq("u", "v", "w", "x", "y", "z") map { FOLVar(_) }
  private val Seq(a, b, c) = Seq("a", "b", "c") map { FOLConst(_) }

  val cycleImpliesEqual =
    new Lemma(
      ("eqrefl" -> All(x, x === x)) +:
      ("eqsymm" -> All(x, All(y, (x === y) --> (y === x)))) +:
      ("eqtrans" -> All(x, All(y, All(z, ((x === y) & (y === z)) --> (x === z))))) +:
      ("eqfcongr" -> All(x, All(y, All(u, All(v, ((x===y) & (u===v)) --> (f(x,u) === f(y,v))))))) +:
      ("fcomm" -> All(x, All(y, f(x, y) === f(y, x)))) +:
      ("fassoc" -> All(x, All(y, All(z, f(f(x, y), z) === f(x, f(y, z)))))) +:
      Sequent()
      :+ ("goal" -> ((f(a, b) === a) & (f(b, c) === b) & (f(c, a) === c)) --> ((a === b) & (b === c)))
    ) {
      use(cut("cf",
        All(x, All(y, All(z, ((f(x, y) === x) & (f(y, z) === y)) --> (f(x, z) === x))))
        & All(u, All(v, ((f(u, v) === u) & (f(v, u) === v)) --> (u === v)))))

      use(forget("goal"))
      use(destruct("cf") onAll decompose())

      // transitivity
      use(chain("eqtrans").subst(y -> f(f(x,y),z))); use(destruct("cf"))
      use(chain("eqsymm")); use(chain("eqfcongr")); use(destruct("cf")); use(chain("eqrefl")); use(prop())
      use(chain("eqtrans").subst(y -> f(x,f(y,z))); use(destruct("cf"))
      use(chain("fcomm"))
      use(chain("eqtrans").subst(y -> f(x,y))); use(destruct("cf"))
      use(chain("eqfcongr")); use(destruct("cf")); use(chain("eqrefl")); use(prop())
      use(prop())

      // anti-symmetry
      use(chain("eqtrans").subst(y -> f(u,v))); use(destruct("cf"))
      use(chain("eqsymm")); use(prop())
      use(chain("eqtrans").subst(y -> f(v,u))); use(destruct("cf"))
      use(chain("fcomm"))
      use(prop())

      // right side of the cut
      use(decompose()); use(destruct("cf")); 
      use(destruct("goal") onAll (chain("cf_2") then destruct("goal") then prop()));

      // f(b,a)=b
      use(chain("cf_1").subst(y -> c)); use(destruct("goal") onAll prop())

      // f(c,b)=c
      use(chain("cf_1").subst(y -> a)); use(destruct("goal") onAll prop())

    } qed

}
```

* `decompose` and `destruct` share the same two letter prefix, and perform similar operations.

**Comment by gebner** [comment]
Examples for further tactics:

# Meta tactics

## `orElse`

```scala
tactic1 orElse tactic2
```

This should probably be a method on `Tactical` (and `Tactic` maybe): try
`tactic1`, and if it fails use `tactic2`.

(`orElse` makes the AxiomTactic much simpler: `LogicalAxiomTactic() orElse
  TopAxiomTactic() orElse BottomAxiomTactic() orElse ReflexivityAxiomTactic()`)

## `repeat`

```scala
repeat(tactical)
```

(It's fine if we call it `RepeatTactic` for now.)
Do `tactical` zero or more times as long as it doesn't fail.

# Complex tactics

## `decompose()`

(It's fine if we call it `DecomposeTactic` for now.)

Example:
```
label1 : exists x, p(x) & q(x)
...
:-
label2 : forall y, p(y) -> (q(y) | r(y))
...
```
Result:
```
label1_1 : p(x)
label1_2 : q(x)
label2_1 : p(y)
...
:-
label2_2_1 : q(y)
label2_2_2 : r(y)
...
```

Should do all unary rules that are unambiguous (i.e. not forall-left or
exists-right where you need to specify a term).

This tactic should be fairly simple to implement: `repeat(AndLeftTactic() orElse ...)`

## `destruct`

Example:
```
...
:-
label: a & (b & c)
```
Result after `destruct("label")`: two subgoals:
```
...
:-
label: a 
```
and
```
...
:-
label: b & c
```

Example:
```
...
:-
label: a | (b | c)
```
Result after `destruct("label")`: 
```
...
:-
label_1: a
label_2: b | c
```

Should do just the applicable rule, once, at the specified label.

## `chain`

```scala
chain(hyp).at(target)
```
 
Takes two labels `hyp` and `target` (`target` should default to the first/only formula in the succedent).
The `hyp` is the implication/universally quantified formula which we want to "use/apply" at `target`.

Example:
```
hyp : forall x, q(x) -> p(f(x))
...
:-
target : p(f(f(c)))
```
Result after `chain("hyp")`:
```
hyp : forall x, q(x) -> p(f(x))
...
:-
target : q(f(c))
```

Example:
```
hyp : forall x, p(f(x))
...
:-
target : p(f(f(c)))
```
Result after `chain("hyp")`: subgoal is solved!

Those were probably the most important two.  Now come a few nice-to-have
examples, which might not be used that extensively:

Example:
```
hyp : forall x, q(x) -> p(f(x))
target : q(c)
...
:-
...
```
Result after `chain("hyp").at("target")`:
```
hyp : forall x, q(x) -> p(f(x))
target : p(f(c))
```

Example:
```
hyp : forall x, r(x) -> (q(x) -> p(f(x)))
...
:-
target : p(f(f(c)))
```
Result after `chain("hyp")`: two subgoals:
```
hyp : forall x, r(x) -> (q(x) -> p(f(x)))
...
:-
target : r(f(c))
```
and
```
hyp : forall x, r(x) -> (q(x) -> p(f(x)))
...
:-
target : q(f(c))
```

**Comment by shetzl** [comment]
I'd like to add two more to this list:

* prop: apply solvePropositional to a goal which contains only propositional formulas

* prover9: apply prover9 to a goal which contains only first-order formulas

These will come in handy to reduce the effort required for formalising a proof.

**Comment by gebner** [comment]
@alexanderbirch Would you do us the honor of closing this bug?

**Comment by alexanderbirch** [comment]
I suppose that this is what you meant, even though I would not go as far as calling it a bug :-)

**Comment by gebner** [comment]
You are, of course, right.  It's called an *issue*. :smile:
