### ISSUE TITLE
RobinsonToLK fails to construct proof

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#278]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on January 26, 2015 14:42:51_

When running the cut-introduction algorithm, we need to generate a propositional proof. This is done using prover9 and the resolution refutation obtained needs to be transformed into an LK proof. For the two files bellow, this transformation fails.

scala> val p = loadProver9LKProof("testing/TSTP/prover9/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out")

scala> val p = loadProver9LKProof("testing/TSTP/prover9/SWW/SWW101+1/Prover9---1109a.THM-Ref.s.out")

Running cut-introduction on any of them return an error:

scala> cutIntro.one_cut_one_quantifier(p)

at.logic.calculi.lk.base.LKRuleCreationException: Sequent [...S1...] cannot be reached from [...S2...] by weakenings and contractions.
  at at.logic.calculi.lk.WeakeningContractionMacroRule$.apply(macroRules.scala:1335)
  at at.logic.algorithms.resolution.RobinsonToLK$.apply(robinson.scala:35)
  at at.logic.provers.prover9.Prover9Prover.getLKProof(Prover9.scala:424)
  at at.logic.provers.eqProver.EquationalProver.getLKProof(EquationalProver.scala:25)
  at at.logic.algorithms.cutIntroduction.CutIntroduction$.buildProofWithCut(CutIntroduction.scala:576)

I investigated the sequents for the first example (SET245-6) and indeed they have different formulas (the sections delimited by *'s):

S1: 
*****************************************************
¬=(restrict(null_class, x, y), null_class),
=(intersection(cross_product(x, y), null_class), 
restrict(null_class, x, y)),
=(intersection(null_class, cross_product(x, y)), 
restrict(null_class, x, y)),
(¬member(regular(intersection(cross_product(x, y), null_class)), intersection(cross_product(x, y), null_class))∨member(regular(intersection(cross_product(x, y), null_class)), null_class)),
******************************************************
(¬member(regular(α_0), universal_class)∨(¬member(regular(α_0), universal_class)∨member(regular(α_0), intersection(universal_class, universal_class)))),
subclass(α_0, universal_class),
(=(α_0, null_class)∨member(regular(α_0), α_0)),
(¬member(regular(α_0), complement(intersection(universal_class, universal_class)))∨¬member(regular(α_0), intersection(universal_class, universal_class))),
(¬subclass(α_0, universal_class)∨(¬member(regular(α_0), α_0)∨member(regular(α_0), universal_class))) 
:- 
(((=(α_0, null_class)∨member(regular(α_0), α_0))∧(member(regular(α_0), universal_class)∨¬member(regular(α_0), α_0)))∧((¬member(regular(α_0), complement(intersection(universal_class, universal_class)))∨¬member(regular(α_0), universal_class))∨¬member(regular(α_0), universal_class))) 

S2:
******************************************************
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
member(regular(α_0), universal_class),
******************************************************
(¬member(regular(α_0), universal_class)∨(¬member(regular(α_0), universal_class)∨member(regular(α_0), intersection(universal_class, universal_class)))),
subclass(α_0, universal_class),
(=(α_0, null_class)∨member(regular(α_0), α_0)),
(¬member(regular(α_0), complement(intersection(universal_class, universal_class)))∨¬member(regular(α_0), intersection(universal_class, universal_class))),
(¬subclass(α_0, universal_class)∨(¬member(regular(α_0), α_0)∨member(regular(α_0), universal_class))) 
:- 
(((=(α_0, null_class)∨member(regular(α_0), α_0))∧(member(regular(α_0), universal_class)∨¬member(regular(α_0), α_0)))∧((¬member(regular(α_0), complement(intersection(universal_class, universal_class)))∨¬member(regular(α_0), universal_class))∨¬member(regular(α_0), universal_class)))

_Original issue: http://code.google.com/p/gapt/issues/detail?id=278_

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 26, 2015 05:58:03_

The same error shows up frequently for the prover9-files which we cannot import (see Jenkins regression tests - extended output), e.g.:

val p = loadProver9LKProof("testing/TSTP/prover9/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN390+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN001+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 26, 2015 06:00:55_

oops - the first example (SET245-6) should of course not be included.

**Comment by newca12** [comment]
_From [fra...@gmail.com](https://code.google.com/u/108596877348066494139/) on January 28, 2015 02:57:15_

Just chiming in with another proof from prover9 that induces the same error. To reproduce:

val res = loadProver9Proof("closest_sqrt.proof");
val lk = Robinson2LK(res._1, res._3);

**Attachment:** [closest_sqrt.proof](http://code.google.com/p/gapt/issues/detail?id=278#hc3)

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 31, 2015 01:23:02_

The case
val p = loadProver9LKProof( "testing/TSTP/prover9/LCL/LCL230+1/Prover9---1109a.THM-Ref.s.out" )
is interesting. It still worked in r2432 but fails in r2433 . This shows that this RobinsonToLK is sensitive on whether a clause set is treated as a scala Set or a scala List.

**Comment by newca12** [comment]
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on January 31, 2015 01:27:41_

Another interesting case is
val p = loadProver9LKProof( "testing/TSTP/prover9/SYN/SYN001+1/Prover9---1109a.THM-Ref.s.out" )

The resolution refutation consists of a single line which carries out NNF-like rewriting under the label "clausify" with which Robinson2LK cannot deal properly.

**Comment by newca12** [comment]
_From [giselle....@gmail.com](https://code.google.com/u/108711232698608960044/) on February 01, 2015 07:53:26_

In r2445 Fixed examples:

val p = loadProver9LKProof( "testing/TSTP/prover9/LCL/LCL230+1/Prover9---1109a.THM-Ref.s.out" )
val p = loadProver9LKProof("testing/TSTP/prover9/SWW/SWW101+1/Prover9---1109a.THM-Ref.s.out") (running cutIntro)


Still failing:

val p = loadProver9LKProof( "testing/TSTP/prover9/SYN/SYN001+1/Prover9---1109a.THM-Ref.s.out" )
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN390+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")

**Comment by shetzl** [comment]
adding CCs from google code: @shetzl @gisellemnr @quicquid  @frehn

**Comment by frehn** [comment]
I have pushed changes to branch issu278 that, I believe, fixes the fixSymmetry bug. The bugs related to prover9s "efficient" CNF-transformation (i.e. the "still failing" problems from the previous comment) are unaffected by my changes.

**Comment by gisellemnr** [comment]
Thanks Daniel!!

Actually, all the "still failing" examples are affected by your changes. They still fail, true, but now with the following error:

scala> val p = loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")
at.logic.algorithms.resolution.ResolutionException: Resolution Exception: Clause [ :- ] is not reflexivity and not contained in CNF(-s) [
⊥: ο :- ⊥: ο
]
  at at.logic.algorithms.resolution.PCNF$.apply(PCNF.scala:69)
  at at.logic.algorithms.resolution.RobinsonToLK$PCNFMemoTable.getPCNF(robinson.scala:24)
  at at.logic.algorithms.resolution.RobinsonToLK$$anonfun$apply$1.apply(robinson.scala:35)
  at at.logic.algorithms.resolution.RobinsonToLK$$anonfun$apply$1.apply(robinson.scala:35)
  at at.logic.algorithms.resolution.RobinsonToLK$.recConvert(robinson.scala:57)
  at at.logic.algorithms.resolution.RobinsonToLK$.apply(robinson.scala:35)
  at at.logic.cli.GAPScalaInteractiveShellLibrary.Robinson2LK$.apply(GAPScalaInteractiveShellLibrary.scala:1008)
  at at.logic.cli.GAPScalaInteractiveShellLibrary.loadProver9LKProof$.apply(GAPScalaInteractiveShellLibrary.scala:214)
  ... 34 elided

The error is always with the empty clause. Is this the other bug that occurs with the NNF-rewriting?

**Comment by frehn** [comment]
Oh, sorry - I did not realize that the error was different before :-)

I think this is exactly the NNF (CNF?) rewriting bug: prover9 takes the formula and rewrites it to a clause form containing the empty clause (which has the trivial resolution refutation consisting just of the empty clause), whereas our CNF transformation rewrites the formula to a CNF that does not contain the empty clause.

A minimal example:
val f = parseFOL("Imp P P");
val s = FSequent(Nil, f::Nil);
prover9.getProof(s);

**Comment by quicquid** [comment]
Hi Daniel and Giselle!

Since these things are trivial, what about using the internal prover or
forgetful resolution to find a refutation from the clause set? At least
for your minimal example, something like this works (on the cli):

import  at.logic.algorithms.resolution._
refuteFOL(CNFn(parseProver9("P(x) -> P(x)")).map(_.toFSequent))

to make it terminate, i think it is possible to add a counter to the
state of the prover.

what do you think?
cheers, Martin

**Comment by frehn** [comment]
This seems like a reasonable idea! We used to have a whole "proof-import-by-replaying" feature in GAPT, didn't we? Maybe we can simply plug that in to try to derive a clause which is used by prover9 as an initial clause from "our" clause set. This seems like a good "fallback" solution, which it seems we will need anyways, unless someone looks into the prover9 code and reverse engineers how exactly their CNF transformation works.

**Comment by quicquid** [comment]
Hi Daniel, in this case the replay wouldn't work because it tried to
derive resolvent clauses from steps. As far as I see, prover9 doesn't
even output a proof step in case the CNF transformation results in a
trivial clause set. But Tomer's prover we used for the replay still
works (although rather inefficiently :) ), which I also used for the
example above.

**Comment by frehn** [comment]
Hi Martin,

I think there is a misunderstanding: we can always import the prover9 refutation, but sometimes it refutes a clause set that is different to the clause set we expect. At the moment, we run only fixSymmetry to derive automatically such "wrong" clauses from the "correct" ones by applications of symmetry and paramodulation. If that fails, we should try to derive the "wrong" clause from "our clause set" via replay.

In the case of "P => P", we import the trivial resolution refutation consisting only of ":-". "Our clause set" will be ":- P; P :-". Since our clause set does not contain the clause ":-", and we cannot derive ":-" from "our clause set" via symmetry, we should use replay to derive ":-" from ":-P; P :-".

I think what I am suggesting is just a less abstract version of your suggestion, i.e. suggesting which code exactly to use (replay, since we can ask it to derive a given clause from a given clause set), and where to put it (i.e. "after" failing to use fixSymmetry to derive the clause).

**Comment by quicquid** [comment]
Hi Daniel!

This might be some artifact from my prover9 import code: whenever the
proof construction fails, the clause set { :- } is returned without a
proof. The intention was that you would see if a clause set is refutable
even if the proof construction failed. But that is superceded by the
Prover interface, I think.

**Comment by frehn** [comment]
As indicated in my last comment, I wrote some code that improves the "fixSymmetry" method (now called "fixDerivation") by additionally trying to derive the initial clauses of a resolution derivation from a given set of clauses by propositional resolution.

From the four lines given by Giselle above

val p = loadProver9LKProof( "testing/TSTP/prover9/SYN/SYN001+1/Prover9---1109a.THM-Ref.s.out" )
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN390+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")

lines 1 and 3 work now. Lines 2 and 4 still fail, and I think I know the reason: the input formulas in these proofs contain the logical constants top and bottom ($T, $F in prover9 syntax), and I've got a hunch that the import has problems with those.

In any case, I think these errors are not really relevant anymore for cut-introduction. Giselle, can you check whether the original problem still persists (the changes I've mentioned have been pushed to gapt:issue278 as commit 86549845c5073975b58f7a1f0abe70fe5a2debed)? Otherwise I'd propose to close this issue and make a new issue pertaining directly to the import of prover9 refutations containing the logical constants.

I should note that fixDerivation still needs some work to work well in all cases - on the other hand, all tests go through, so it might be fine for now.

**Comment by gisellemnr** [comment]
Hi Daniel,

thank you very much for the fix! I will check the cut-introduction tests
tonight and if all is ok, I will close the issue and push your changes to
master.

In the meantime, you can play around with git's rebasing and rewriting
history to make your commits more self-contained :)  I noticed you have a
commit only to delete a superfluous file. With git you can easily edit the
commit in which this file was added so that it is not added anymore, thus
avoiding the deletion commit. That is a very powerful feature of git which
is very useful for me, as simple fixes can always be done on the commits
themselves rather than being yet another commit (of course it makes more
sense doing this in branches and sending to master only commits we do not
intend to rewrite).

Best,
Giselle

**Comment by frehn** [comment]
Hi Giselle,

thanks for the heads up! I'm still "learning by doing" in git, so I am
quite sorry for my brutish use of the new tool, and very much appreciate
your suggestions. I'll reorganize my commits to the issue278 branch as you
suggest!

Best,
Daniel

**Comment by gisellemnr** [comment]
No need to be sorry :)
I learned this not long ago, and only by doing as well. After a lot of
commits rewriting and detached head states you'll get the gist of it. One
thing that might make it easier for you to make a few tests is to do it on
another branch. This way you don't loose your original commits.

If you are on branch issue278 (you can check this by running git branch
-v), a copy of it can be created by running:

git branch issue278_testing

Then you can checkout to this testing branch and do whatever there. This
will not alter anything on the original issue278.

Have fun!

**Comment by frehn** [comment]
I made some further changes (which fortunately appear to be improvements :-) to the prover9 import in 4e76e2d68444f9eaa43857778bc247e925d5a7ab (OT: I squashed some commits to get a nicer push, but things got slightly messed up since I squashed after pushing to my own branch. Third time's a charm, I do hope!)

**Comment by gisellemnr** [comment]
Of all the proofs raised in this issue, after Daniel's patches the situation is the following:

Cut-intro works on:
val p = loadProver9LKProof("testing/TSTP/prover9/SET/SET245-6/Prover9---1109a.UNS-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SWW/SWW101+1/Prover9---1109a.THM-Ref.s.out")

Loading works for:
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN390+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN001+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof( "testing/TSTP/prover9/LCL/LCL230+1/Prover9---1109a.THM-Ref.s.out" )

Loading fails for:
val p = loadProver9LKProof("testing/TSTP/prover9/SYN/SYN915+1/Prover9---1109a.THM-Ref.s.out")
val p = loadProver9LKProof("testing/TSTP/prover9/SWC/SWC128-1/Prover9---1109a.UNS-Ref.s.out")

with error: Clause [ :- ] is not reflexivity and not contained in CNF(-s) [ some tautology ]

Robinson2LK fails for:
val res = loadProver9Proof("closest_sqrt.proof");
val lk = Robinson2LK(res._1, res._3);

with error: Sequent ... cannot be obtained from ... by weakenings and contractions.
  at at.logic.calculi.lk.WeakeningContractionMacroRule$.apply(macroRules.scala:1297)
  at at.logic.algorithms.resolution.RobinsonToLK$.apply(robinson.scala:36)

I am leaning towards closing this issue in spite of the last error.
I can open another one for the empty clause error.

**Comment by frehn** [comment]
Hi Giselle,

thank you very much for organizing the commits and pushing to master!

Regarding the last failure you report: it is the case that

loadProver9LKProof("closes_sqrt.proof")

runs successfully. I think the reason for this is that in the example, res._3 contains free variables, while the end-sequent constructed in loadProver9LKProof is closed. So it seems while the prover9 import code is improved now, its interfaces still need to be improved and documented - maybe something to be discussed at the next GAPT meeting.

In any case, I think it is a good idea to close this issue and make a new one for the other errors, as you suggest!
