### ISSUE TITLE
veriT.getExpansionSequent( s ) should return expansion sequent of s

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#298]
Do the following in the CLI:
val A = parseProver9( "f(f(a,b),c) = f(a,f(b,c))" )
val T = parseProver9( "f(a,b)=a -> ( f(b,c) = b -> f(a,c)=a )" )
val s = FSequent( List( A ), List( T ))
val verit = new at.logic.provers.veriT.VeriTProver
val E = verit.getExpansionSequent( s ).get

The resulting expansion sequent E is not an expansion sequent of s but of a modified version where T is moved to the antecedent and implications are modified. Instead, an expansion sequent of s should be returned.

Doing
val prover9 = new at.logic.provers.prover9.Prover9Prover
val p = prover9.getLKProof( s ).get
instead yields a proof of s as expected.

@gisellemnr

**Comment by gisellemnr** [comment]
Hi Stefan,

This behaviour is due to the fact that veriT will prove a sequent of the form A1, ..., An |-, so when the sequent is exported to a veriT input file, all its succedents are negated and put on the antecedent. The input file for you example is:
(assert (= (f a (f b c ) ) (f (f a b ) c ) ))
(assert (not (=> (= a (f a b ) ) (=> (= b (f b c ) ) (= a (f a c ) )))))

Therefore, when the output is read, these are the ground formulas on the left side of the sequent. I asked Bruno and apparently there is no way to get this information from the veriT proofs themselves, but we can do the following: take only the eq-axioms from the veriT output and merge them with the initial sequent (which should always be ground) used as an argument of getExpansionSequent. Would you like me to implement this? I don't think it's too hard...

Best,
Giselle.

**Comment by shetzl** [comment]
Hi Giselle,

Yes, this looks like a good solution to me. Please implement it. Thanks!

Best regards,
Stefan

**Comment by gisellemnr** [comment]
Fixed by commit 40c8d7140ee812f14493db04efcca5101a596d8a.
Closing the issue.
