### ISSUE TITLE
veriT interface: constants vs. variables

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#304]
In the CLI execute the following script:

val minisat = new at.logic.provers.minisat.MiniSATProver
val verit = new at.logic.provers.veriT.VeriTProver
val C = parseProver9( "f(x,y) = f(y,x)" )
val AS = parseProver9( "f(x,y)=x -> ( f(y,x)=y -> x=y )" )
val s = FSequent( List( C ), List( AS ))
val E = verit.getExpansionSequent( s ).get
val Edeep = at.logic.calculi.expansionTrees.toDeep( E )
minisat.isValid( Edeep ) 

This returns false, however a look at prooftool( E ) and a quick pencil-and-paper calculation shows that the deep formula of E is valid.

val I = miniSATsolve( at.logic.language.fol.Neg( Edeep.toFormula.asInstanceOf[FOLFormula] )).get 

produces the following interpretation (after sorting):
=(f(x, y), f(y, x)) -> false
=(f(x, y), f(y, x)) -> true
=(f(x, y), x) -> false
=(f(x, y), x) -> true
=(f(y, x), f(x, y)) -> false
=(f(y, x), y) -> false
=(f(y, x), y) -> true
x0: ο -> true
x10: ο -> true
x11: ο -> true
x12: ο -> true
x13: ο -> true
x14: ο -> true
x15: ο -> true
x16: ο -> true
x17: ο -> true
x18: ο -> true
x19: ο -> true
x1: ο -> false
x20: ο -> false
x21: ο -> false
x22: ο -> false
x23: ο -> false
x24: ο -> false
x25: ο -> false
x26: ο -> false
x27: ο -> true
x2: ο -> true
x3: ο -> true
x4: ο -> false
x5: ο -> true
x6: ο -> true
x7: ο -> true
x8: ο -> true
x9: ο -> true
=(x, f(x, y)) -> false
=(x, y) -> false
=(x, y) -> false
x: ο -> false
=(y, f(x, y)) -> false
=(y, f(y, x)) -> false
=(y, x) -> false

Note that the following atoms are assigned two different values: 
=(f(x, y), f(y, x))
=(f(x, y), x)
=(f(y, x), y)

There are also other multiple (but consistent) assignments.

@frehn @DarwinsBuddy

**Comment by shetzl** [comment]
In the above example also Sat4J and proveProp say that EDeep is not valid. Appending the following:
val x = FOLVar( "x" )
val a = FOLConst( "a" )
val sxa = at.logic.language.fol.Substitution( x, a )
val y = FOLVar( "y" )
val b = FOLConst( "b" )
val syb = at.logic.language.fol.Substitution( y, b )
val sub = sxa.compose( syb )
sub( Edeep.toFormula )

produces a formula which contains x's and y's in the instances of symmetry and transitivity of equality generated by veriT.

@gisellemnr: this now looks more connected to veriT export / parsing than to Tseitin and minisat. Could it be that the FOLVars x and y in AS and C are treated as constants by veriT but the instances generated by veriT refer to FOLConsts x and y instead of the FOLVars x and y?

**Comment by gisellemnr** [comment]
The problem lies in fact in parseProver9. Look at the following execution:

gapt> val px = parseProver9("p(x)")
px: at.logic.language.fol.FOLFormula = p(x)

gapt> val x = px match { case Atom(_, List(x)) => x }
x: at.logic.language.fol.FOLTerm = x

gapt> x.getClass
res5: Class[_ <: at.logic.language.fol.FOLTerm] = class at.logic.language.fol.FOLVar

gapt> val pa = parseProver9("p(a)")
pa: at.logic.language.fol.FOLFormula = p(a)

gapt> val a = pa match { case Atom(_, List(a)) => a }
a: at.logic.language.fol.FOLTerm = a

gapt> a.getClass
res6: Class[_ <: at.logic.language.fol.FOLTerm] = class at.logic.language.fol.FOLConst

It parses x as a variable and a as a constant. This might be intentional... look at lines 37 and 38 of file parsing/language/prover9/Prover9TermParser.scala.

**Comment by shetzl** [comment]
Yes, this is intentional. In this example I want to use parseProver9 for generating formulas which contain FOLVars and veriT to prove the sequent thus constructed.

**Comment by gisellemnr** [comment]
I see... but the formula given to veriT is ground... so it definitely interprets x and y as constants. What it might happen is that the expansion sequent generated later takes the versions of AS and C with x and y as variables. Because of a previous issue with the negation of input formulas, we discard the input as generated by the veriT parser and just add the one which was the parameter of the method.

If I understand correctly, what you wanted as an expansion sequent was:
AS[const], C[const], EqAxioms

And in turn you get:
AS[var], C[var], EqAxioms

Is this correct? If so, the fix I see for this issue is to transform all variables of the input sequent into constants by hand... What do you think?

**Comment by shetzl** [comment]
What I want as expansion sequent is
AS[var], C[var], EqAxioms[var]

what I get instead is
AS[var], C[var], EqAxioms[const]

whose deep formula is not a tautology (contrary to what I wrote in my opening comment for this issue).

[ I need the var-version because I later want to build an LK proof which quantifies over the variables in AS and C for the cut-introduction example. ]

After sleeping over it ;-) I think the issue boils down to the question what the specification of the method VeriTProver.getExpansionSequent should be. I would say that in any case if this method does not return None it should return an ExpansionSequent whose deep formula is a tautology. This is not the case here, so something needs to changed there.

The main question that remains then is what to require on the input sequent s of that method. It seems to me that currently the implicit requirement is that s does not contain quantifiers nor (free) variables (nor any predicate symbol different from "=" ?). I see two options:
1) make this implicit assumption explicit by throwing an exception if the input sequent contains inadmissible syntactic objects (like variables)
2) allow also free variables and do a variable -> constant -> variable conversion within veriT (but still throw an exception if e.g. a quantifier is encountered)

Implementing 1) would then require the user of the veriT-packages to do this conversion manually if needed. It may thus put a little more work on the user but may lead to a cleaner separation of different functionality... what do you think?

**Comment by frehn** [comment]
I did not have time to think deeply about the issue at hand, but let me note that this question does not only concern VeriT, but all provers - in prover9, for example, we implement Stefan's suggestion 2) (see Prover9Prover.getRobinsonProof and the comment before it). 

If you come up with a good solution, please keep in mind that such a solution could (should?) be uniform across all provers (i.e. classes implementing the Prover interface).

My 2cents are: Free variables should be considered implicitly universally quantified. This implies that if we run methods that "prove" something (i.e. getProof, isValid), as opposed to "refuting" something, the free variables should be interpreted as constants (as would be obtained by skolemizing the universal closure of the formula).

**Comment by gisellemnr** [comment]
Sorry for the delay on addressing this... a fix is on commit a57cdb41373f8e85fb2f820e569f627fb3b93fbd.
I'll wait for you to test it and close this issue.

**Comment by shetzl** [comment]
The following is the script which started this issue with package names adapted:

val minisat = new at.logic.gapt.provers.minisat.MiniSATProver
val verit = new at.logic.gapt.provers.veriT.VeriTProver
val C = parseProver9( "f(x,y) = f(y,x)" )
val AS = parseProver9( "f(x,y)=x -> ( f(y,x)=y -> x=y )" )
val s = FSequent( List( C ), List( AS ))
val E = verit.getExpansionSequent( s ).get
val Edeep = at.logic.gapt.proofs.expansionTrees.toDeep( E )
minisat.isValid( Edeep )

Now minisat.isValid( Edeep ) returns true as it should. But prooftool( E ) shows that the bound variables in the symmetry- and transitivity-axioms are prefixed by colons. This makes it difficult to read and should be avoided.

I am not sure I understand why we need the colons. A substitution is a mapping which is the identity on all but the specified variables. So the term x matches the term y with the substitution [x\y] and the term x matches the term x with the subsitution id. There is no problem with using the same name for bound and free variables.

**Comment by gisellemnr** [comment]
There shouldn't be. But it seems that the FOLMatchingAlgorithm returns an empty list of substitutions when they are all ids.
If I use x and y as variables, I get the following expansion sequent:
E: at.logic.gapt.proofs.expansionTrees.ExpansionSequent = ExpansionSequent(List(WeakQuantifier(∀x.∀y.∀z.((=(x, y)∧=(y, z))⊃=(x, z)), List()), WeakQuantifier(∀x.∀y.(=(x, y)⊃=(y, x)), List((WeakQuantifier(∀y0.(=(f(y, x), y0)⊃=(y0, f(y, x))), List()),f(y, x)))), Atom(=(f(x, y), f(y, x)))), List(Atom(=(f(x, y), x))⊃Atom(=(f(y, x), y))⊃Atom(=(x, y))))

Note that the lists are all empty.

If I change your commands to:
gapt> val C = parseProver9( "f(x0,y0) = f(y0,x0)" )
C: at.logic.gapt.language.fol.FOLFormula = =(f(x0, y0), f(y0, x0))

gapt> val AS = parseProver9( "f(x0,y0)=x0 -> ( f(y0,x0)=y0 -> x0=y0 )" )
AS: at.logic.gapt.language.fol.FOLFormula = (=(f(x0, y0), x0)⊃(=(f(y0, x0), y0)⊃=(x0, y0)))

I get the expansion tree:
E: at.logic.gapt.proofs.expansionTrees.ExpansionSequent = ExpansionSequent(List(WeakQuantifier(∀x.∀y.∀z.((=(x, y)∧=(y, z))⊃=(x, z)), List((WeakQuantifier(∀y.∀z.((=(y0, y)∧=(y, z))⊃=(y0, z)), List((WeakQuantifier(∀z.((=(y0, f(x0, y0))∧=(f(x0, y0), z))⊃=(y0, z)), List((Atom(=(y0, f(x0, y0)))∧Atom(=(f(x0, y0), x0))⊃Atom(=(y0, x0)),x0))),f(x0, y0)))),y0), (WeakQuantifier(∀y.∀z.((=(y0, y)∧=(y, z))⊃=(y0, z)), List((WeakQuantifier(∀z.((=(y0, f(y0, x0))∧=(f(y0, x0), z))⊃=(y0, z)), List((Atom(=(y0, f(y0, x0)))∧Atom(=(f(y0, x0), f(x0, y0)))⊃Atom(=(y0, f(x0, y0))),f(x0, y0)))),f(y0, x0)))),y0))), WeakQuantifier(∀x.∀y.(=(x, y)⊃=(y, x)), List((WeakQuantifier(∀y.(=(f(y0, x0), y)⊃=(y, f(y0, x0))), List((Atom(=(f(y0, x0), y0))⊃Atom(=(y0, f(y0, x0))),y0))),f(y0, x0)), (WeakQuantifier(∀y.(=(y0, y)⊃=(y, y...

with all the correct term substitutions.
I am trying to understand the code in FOLMatchingAlgorithm to see why this happens. Is this the expected behaviour or is it a bug?

**Comment by shetzl** [comment]
FOLMatchingAlgorithm does not compute a list of substitutions, but an Option[FOLSubstitution].

I get
gapt> val S = parseProver9( "x=y -> y=x" )
S: at.logic.gapt.language.fol.FOLFormula = (=(x, y)⊃=(y, x))

gapt> val sigma = FOLMatchingAlgorithm.matchTerms( S, S ).get
sigma: at.logic.gapt.language.fol.FOLSubstitution = Substitution()

gapt> sigma(S)
res15: at.logic.gapt.language.fol.FOLFormula = (=(x, y)⊃=(y, x))

which is correct: sigma is the identity substitution.

**Comment by gisellemnr** [comment]
I understand. The problem then is on the method formulaToExpansionTree. If the substitution passed as a parameter is empty, it cannot find the variables used to replace each quantifier and thus does not generate any instances... Should I treat this as a special case on formulaToExpansionTree??

**Comment by shetzl** [comment]
There is no such thing as an empty substitution. A substitution is a mapping of variables to terms which is the identity on all but finitely many variables. The representation [x_1\t_1,...,x_n\t_n] includes implicitely the information that all y different from any of the x_i are mapped to y. 

Why do you include the check on whether s.domain.contains( v ) in formulaToExpansionTree in the weak quantifier cases? In my opinion, formulaToExpansionTree( \forall x \forall y ( x=y -> y=x ), id ) should just be the expansion tree
\forall x \forall y ( x=y -> y=x ) +^x (
    \forall y ( x=y -> y=x ) +^y
        ( x=y -> y=x )
)

Also, why is there an assertion for positive universal but not for negative existential in formulaToExpansionTree?

**Comment by gisellemnr** [comment]
>
> There is no such thing as an empty substitution. A substitution is a
> mapping of variables to terms which is the identity on all but finitely
> many variables. The representation [x_1\t_1,...,x_n\t_n] includes
> implicitely the information that all y different from any of the x_i are
> mapped to y.
>
> Why do you include the check on whether s.domain.contains( v ) in
> formulaToExpansionTree in the weak quantifier cases? In my opinion,
> formulaToExpansionTree( \forall x \forall y ( x=y -> y=x ), id ) should
> just be the expansion tree
> \forall x \forall y ( x=y -> y=x ) +^x (
> \forall y ( x=y -> y=x ) +^y
> ( x=y -> y=x )
> )
>
I implemented this to get an expansion tree of a formula used in a proof.
If it is a weakly quantified formula, it might have many instantiations for
the same bound variable. This is why I have this check. I take the
substitutions that bind the variable and construct the rest of the tree
with them.

> Also, why is there an assertion for positive universal but not for
> negative existential in formulaToExpansionTree?
>
The assertion is making sure that a strong quantifier is instantiated only
once. Since the StrongQuantifier takes one instance (and not a list of
them, as is the case for the weak quantifier), I did not know what to do in
case a StrongQuantifier is instantiated with more than one term in a proof.
So I added this assertion. Gladly, it was never reached so far...

**Comment by shetzl** [comment]
After looking at formulaToExpansionTree more closely I see that the problem is more subtle than I thought. It seems that formulaToExpansionTree implicitely makes some assumptions on the substitutions (maybe that domain(sigma) and range(sigma) are disjoint?) without making this explicit in either the documentation or trough an assertion. For example the following code 

import at.logic.gapt.proofs.expansionTrees.formulaToExpansionTree
import at.logic.gapt.proofs.expansionTrees.ExpansionSequent

val F = parseProver9( "(all x all y P(x,y))" )
val x = FOLVar( "x" )
val y = FOLVar( "y" )
val s = FOLSubstitution( Map( (x,y), (y,x) ))
val E  = ExpansionSequent( formulaToExpansionTree( F, List( s ), false )::Nil, Nil )

produces an E with an empty list of instances for the second quantifier (because it is renamed by substitution). This E cannot be displayed by prooftool. The specification of formulaToExpansionTree should be made more precise to include the exact conditions required of the substitions.

In general, I would rather avoid references to bound variables by name. In my opinion, a cleaner implementation of formulaToExpansionTree would be one that takes - instead of the substitutions - the instances which are to be generated.

For now, I think the easiest way out is that I rename the variables to x0 and y0 in my script, then we can go back to x,y,z, etc. for the equality axioms. I am therefore closing this issue. Thanks for the fix!

"
The assertion is making sure that a strong quantifier is instantiated only once. Since the StrongQuantifier takes one instance (and not a list of them, as is the case for the weak quantifier), I did not know what to do in case a StrongQuantifier is instantiated with more than one term in a proof. So I added this assertion. Gladly, it was never reached so far...
"
The point of my comment was only that positive universal and negative existential should be treated the same way: if there is an assertion for than there should be one for the other.

**Comment by gisellemnr** [comment]
I see the problem... indeed I should make the assumptions clearer through an assertion. I am adding this in a commit soon.

"
In general, I would rather avoid references to bound variables by name. In my opinion, a cleaner implementation of formulaToExpansionTree would be one that takes - instead of the substitutions - the instances which are to be generated.
"

It might be clearer my reason to use substitution if I explain where this comes from. The method was implemented to deal with leancop proofs, there the bindings are associated with clauses, not input formulas. I try my best to match these elements, to get a mapping from the variables used in the clauses to the variables used in the formulas (they are renamed during DNF transformation). The final substitution used is a combination of this mapping and the bindings present in the proof. 
Of course I could instantiate all the formulas and give these to formulaToExpansionTree, but this would require a matching algorithm to find the substitutions which I already had in the first place. I didn't think about renaming though... because it does not happen in leanCoP.

I guess that, given the right scenario, we can use a faster method, otherwise we need something with matching.

**Comment by shetzl** [comment]
Thanks for the fix! I see, then basing this on substitutions makes more sense. I am fine with this implementation as long as it is clear what the preconditions are.

**Comment by quicquid** [comment]
Since we have a clause matching algorithm: is there a reason not to use it? It's what i do in the ceres algorithm when i need to find a projection for a clause.
