### ISSUE TITLE
ReplayTest runs as an infinite loop in the regular-layers branch

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#327]
```
$ git checkout regular-layers
$ sbt 'testOnly *Replay*'
```

In particular, it seems to hang on the "work on the tape-in clause set" example.

**Comment by shetzl** [comment]
@shaolintl This is an infinite loop in atp. Tomer, may I ask you to have a look at this? Gabriel tried debugging it but it seems quite hard to figure out what is going on if one does not know the details of the atp-prover well. Thank you!

**Comment by shaolintl** [comment]
Sure, but it will have to wait until Wednesday.

**Comment by shaolintl** [comment]
ATP just executes a possibly infinite stream of commands.
The Prover9Init command intialize the stream with finitely many commands according to the resulted proof where it uses Replay to search for macro steps in the proof (not corresponding to Robinson's).
The Replay command starts a new proof search (on a new prover instance). This search is using an infinite sequence of a normal proof search sequence (see the ReplayCommand for the exact steps which are being tried). Replay is using a MacroCommand for optimization but this can be removed and then printing the commands (Prover.scala 118), shows you the actual search which is being tried.

I did that and it seems to me there is no bug in atp but that replay fails to find a solution (in a reasonable time). Since the integration of eprover was done by Martin, I attach him to the loop. Maybe he can tell us more about what is the problem.

Anyway, I think that the best thing to do is to consider this relay steps

 closely and see why a proof was not found. It might be that there is a bug in the components of ATP, i.e. unification is not working properly, etc. But without testing all the components separately, one will need to closely look on the steps taken by ATP and see why it failed to find a proof.

I put below the first commands of this specific replay (it seems one cannot add files to github?! and how can I cc people without having to assign the issue to them first?).

Trying to prove  ladr3(ladr2(A,B))=ladr1 :- ladr3(ladr2(C,ladr2(ladr2(A,B),ladr0)))=ladr0  from :
 :- X=X
ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- 
 :- ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(B,A))=ladr0

command: [31mclass at.logic.gapt.provers.atp.commands.replay.SetClauseWithProofCommand[0m, data: ()
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SetTargetClause[0m, data: ()
command: [31mclass at.logic.gapt.provers.atp.commands.refinements.simple.SimpleRefinementGetCommand[0m, data: ()
command: [31mclass at.logic.gapt.provers.atp.commands.robinson.VariantsCommand$[0m, data: (InitialType( :- X=X),InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ))
command: [31mclass at.logic.gapt.provers.atp.commands.logical.DeterministicAndCommand[0m, data: (Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)),Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr3(ladr2(A0,B0))))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr3(ladr2(A0,B0))))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(A0,B0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(A0,B0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> A0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> A0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> B0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> B0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr1))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1,ladr3(ladr2(A0,B0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr1))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(ladr2(ladr2(A0,B0),ladr0),C0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(ladr2(ladr2(A0,B0),ladr0),C0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(ladr2(A0,B0),ladr0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(ladr2(A0,B0),ladr0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(A0,B0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr2(A0,B0)))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> A0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> A0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> B0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> B0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> C0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> C0))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr1))
command: [31mclass at.logic.gapt.provers.atp.commands.sequents.SimpleForwardSubsumptionCommand[0m, data: Para(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , Vr( :- X0=X0, InitialType( :- X=X), Substitution(X -> X0)), Vr(ladr3(ladr2(A0,B0))=ladr1,ladr3(ladr2(ladr2(ladr2(A0,B0),ladr0),C0))=ladr1 :- , InitialType(ladr3(ladr2(A,B))=ladr1,ladr3(ladr2(ladr2(ladr2(A,B),ladr0),C))=ladr1 :- ), Substitution(C -> C0,B -> B0,A -> A0)), Substitution(X0 -> ladr1))

**Comment by gebner** [comment]
Thanks for looking into this issue!

You can CC people like this: @quicquid -- they will be automatically subscribed to this issue.

As for file uploads, I guess the "official" github way is to use https://gist.github.com/

**Comment by shaolintl** [comment]
thanks.

**Comment by shaolintl** [comment]
Following Gabriel's comment:

https://gist.github.com/shaolintl/b299af872187bf8e66a5

**Comment by quicquid** [comment]
Hi, afaik there is no eprover integration in gapt. The replay code is also independent of the Prover9 import. I'll still have a look - this test was already failing some months ago, but I don't remember how i fixed it. I'll report back when I know more.

**Comment by shaolintl** [comment]
Sorry Martin, I meant prover9.

**Comment by quicquid** [comment]
Just a small comment: even with the offending test commented out, there is a loop in the tests(I stopped execution after 30 minutes). At the cli, :load examples/hol-tape/ntape-script.scala apparently loops during struct extraction and sbt 'testOnly *TapeTest*' loops too (even when I skip the ceres test).

**Comment by quicquid** [comment]
And a second comment: the change which made the replay test pass again was to change a test of Sequent equality to SyntacticMultiSet equality. Perhaps something is wrong with equality?

**Comment by gebner** [comment]
> Perhaps something is wrong with equality?

Thanks for the pointer!  It unfortunately didn't help with the test, but at least I found a nice bug: https://github.com/gapt/gapt/commit/d995cdbfcd57ed501c2b96836259b89e2ff85dc4

**Comment by gebner** [comment]
I'm not sure how this happened exactly, but it was due to a conversion of VariantSymbols to StringSymbols.  Fixed in 5d5272d162db3dd5ecfc4a31140592558e57566c

**Comment by quicquid** [comment]
Thanks for finding the bug, I was looking in completely different places. Is it possible that an FOL algorithm unapplies an Atom/Function and recreates it from the String returned, resulting in a StringSymbol?

**Comment by gebner** [comment]
> Is it possible that an FOL algorithm unapplies an Atom/Function and recreates it from the String returned, resulting in a StringSymbol?

Definitely, although I don't think I changed anything there; the FOLFunction matchers return strings in the master branch as well.
