### ISSUE TITLE
lambda terms displayed incorrectly by toString

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#337]
At the CLI enter
App( Abs( Var( "x", Ti ), Var( "x", Ti )), Const( "c", Ti ))
This results in
res1: at.logic.gapt.expr.App = (λx.x c)

However, in standard lambda calculus notation this should be written as
(λx.x) c
or 
((λx.x) c)

For a reference for the notation, see the start of Chapter 2 in Barendregt: The Lambda Calculus, 1985.

**Comment by gebner** [comment]
I have added parentheses around lambda abstractions in 52e63102a1afa60552998c7080bae9cb3f104ac4.

> For a reference for the notation, see the start of Chapter 2 in Barendregt: The Lambda Calculus, 1985.

I really don't think we should rely on Barendregt for our syntax, aside from using it as a historical reference that application should bind more tightly than abstraction; but that one is true in pretty much every functional language.

In any case I think it would be nice to have a unified input/output format, with well-defined operator precedence, a pretty-printer that wisely adds whitespace and parens only when necessary, and then a parser so that you can copy-paste the toString output and get back a lambda term, and maybe even a quasi-quoting macro. *dreams*
