### ISSUE TITLE
Unnecessary regularization in cut-elimination?

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#416]
Apparently we maintain the invariant that the proof we reduce is regular--is there any reason for that?  Can we remove regularization here?

**Comment by quicquid** [comment]
For CERES, we need regular proofs. The reason is that the eigenvariables in the xioms become the variables of the characteristic clause set. A recombination of axioms from different branches might accidentally unify variables - its a bit like  \A:x P(x) /\ A:x Q(x) vs \A:x (P(x) /\ Q(x)). For the Gentzen method, this is not necessary.

**Comment by gebner** [comment]
I was only thinking of the Gentzen method, actually.  But you're right, for CERES the proofs need to be regular.

**Comment by shetzl** [comment]
Well, in the traditional textbook formulation also the Gentzen method needs regularization. In particular it needs renaming of eigenvariables which are duplicated at the reduction of a contraction. Otherwise a combination of this duplication and rule permutations can lead to a situation where two strong quantifier rules with the same eigenvariable are on the same branch. Substituting for the lower will then fail at the upper.

I do not know whether the new variant of applySubstitution which renames eigenvariables on the fly gets rid of this problem. One should not forget that rule permutations can move formulas around and hence destroy the "binding structure" of strong quantifier rules.

**Comment by gebner** [comment]
Stefan, you're right--this is a proof where we need to either regularize or rename eigenvariables during rank-reduction:
![cutelim-regular](https://cloud.githubusercontent.com/assets/313929/10507227/4be8c37a-731f-11e5-9e36-a36e98c4990a.png)
