### ISSUE TITLE
prooftool doesn't support proofs with ternary rules

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#426]

**Comment by mrukhaia** [comment]
According to prooftool's current design, it is not hard to add ternary
rules to prooftool, if there is an object like TernaryTreeProof or
something. Generalizing this to 4 and N-ary rules would need more effort
and probably a complete change of design.

Best regards
Mikheil Rukhaia

**Comment by gebner** [comment]
> Generalizing this to 4 and N-ary rules would need more effort and probably a complete change of design.

Ah, that's too bad.  Ternary was just an example, the current induction rule is actually n-ary.  I thought this would just require a small change in [`DrawSequentProof.initialize()`](https://github.com/gapt/gapt/blob/bafa3edbcfb5d08209b8c73e7c5cb04980e7a1e4/src/main/scala/at/logic/gapt/prooftool/DrawSequentProof.scala#L78-L93).

**Comment by mrukhaia** [comment]
The problem is that the layout object in DrawSequentProof.initialize()
<https://github.com/gapt/gapt/blob/bafa3edbcfb5d08209b8c73e7c5cb04980e7a1e4/src/main/scala/at/logic/gapt/prooftool/DrawSequentProof.scala#L78-L93>
has
only three horizontal "places", east, center and west, so we could have
three branches easily. One solution about N-ary rules can be to place
recursively other layouts e.g. in center until we reach N branches, but
then it will be much harder to draw lines properly.

Best regards
Mikheil Rukhaia

**Comment by gebner** [comment]
Fixed with the merge of the `prooftool-wip` branch.
