### ISSUE TITLE
decompose tactic has problems with label generation

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#470]
See the `decomposeLemma` in `complex.scala`:
```scala
Lemma(
    Sequent( Seq( "label1" -> parseFormula( "(exists x (p(x) & q(x)))" ) ),
      Seq( "label2" -> parseFormula( "(all y (p(y) -> (q(y) | r(y))))" ) ) )
  ) {
      decompose
    }
```
fails with
```
at.logic.gapt.proofs.gaptic.QedFailureException: Proof not completed. There are still 1 unproved sub goals:
label1_0: p(x)
label1_0: q(x)
label2_0: p(y)
:-
label2_1_0: q(y)
label2_1_1: r(y)
```

Note the duplicate labels `label1_0` and `label1_0`.

**Comment by alexanderbirch** [comment]
Now fixed. Btw, I think with the automatic use of the qed method after a
Lemma, it becomes somewhat impossible to test tactics on unfinished proofs,
since it will throw an QedFailureException.

Maybe there should be a way to indicate that a proof is incomplete? Just an
idea, since there are quite a few tests that currently are not expected to
provide complete proofs :).


Alexander Birch

2016-01-22 14:50 GMT+01:00 Gabriel Ebner <notifications@github.com>:

**Comment by gebner** [comment]
In practice, you always want all proofs to be complete.  Making it possible to have incomplete proofs by default is IMHO just a source of subtle bugs, since forgetting a `qed` at the end is an easy mistake to make.

I think it is important here to make it very explicit if you choose to write a lemma with an incomplete proof.  Maybe Isabelle-style by writing `sorry` for the subgoals you don't want to prove, or by having a separate `PartialLemma`/`IncompleteLemma`/... call.
