### ISSUE TITLE
Cannot extract expansion proof from new tape proof because of definitions

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#471]
```
scala> LKToExpansionProof(tape.p)
scala.MatchError: [p21] A :- I(1), I(0)    (DefinitionRightRule(p20, Suc(0), I(0)))
```

i.e., `LKToExpansionProof` fails because it cannot handle definition rules.  We should probably add a `tape.definitions: Map[Const, LambdaExpression]` map so that we can eliminate the definitions.

This also applies to the lattice proof, once it uses definitions.

cc @shetzl @alexanderbirch

**Comment by alexanderbirch** [comment]
The lattice proof might give some problems in this regard, since sometimes the predicate
leq(x,y) -> cap(x, y) = x 
has to unfolded inside formula (sorry if I remember the definition incorrectly).

Even doing this with definition rules is a bit cluncky, since I could not come up with an automatic way to unfold an entire formula, so this is done rather manually.

Anyway, I just mean that I really don't know how this map needs to look. Btw, I hope to commit an updated proof soon :).

**Comment by shetzl** [comment]
Eliminating defintions is one option. Another interesting option may be to incorporate definitions into expansion trees - at least for definitions of type o this is reasonably natural with a definition node whose shallow formula is just the defined atom and whose deep formula is the deep formula of the defining formula.

**Comment by loewenheim** [comment]
See commit 3628804d6c12377a8fecbdc326a4330ce6a8acee for a simple implementation of an expansion tree definition node. At this time, it can only deal with atomic definitions.

**Comment by loewenheim** [comment]
Actually, a question just occurred to me: Given the very restricted expansion tree definition nodes, would it make sense to restrict the LK definition rule in a similar way? What I mean by that is that the definition rule would only allow the replacement of an entire formula by a new atomic symbol, i.e. there would be no replacement *within* formulas. Is that too restrictive?

**Comment by quicquid** [comment]
The way I understand a definition D(x1,...,xn) := F(x1,...,xn) is that D needs all the free variables of F as arguments. Otherwise, you can create proofs where eigenvariable conditions are violated after definition elimination. For instance consider:

    Q(x) :- Q(x)
    --------------- d:l
        D :- Q(x)
  ------------------------- all:r
     D :- (forall x Q(x))
  ------------------------- d:l
   Q(x) :- (forall x Q(x))

This means that definitions without arguments can only stand for variable-free formulas, which I consider a severe restriction.

**Comment by gebner** [comment]
@quicquid That's a good point.  Right now we want to consider definitions as pair of a constant and the expansion as a lambda expression--so `D -> \lambda x1...xn Fx1...xn` in your example.  But as you correctly point out, the expansion must not have any free variables.  What's implemented in the expansion trees at the moment is the expansion of the head symbol of an atom.

**Comment by gebner** [comment]
> We should probably add a tape.definitions: Map[Const, LambdaExpression] map so that we can eliminate the definitions.

Done.
