### ISSUE TITLE
Does CERES require atomic axioms / regular proofs?

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#474]
Currently, [one of the regression tests](http://compile.logic.tuwien.ac.at/job/gapt%20extended%20testing/97/testReport/Prover9TestCase/CERES%20(cut-intro)/GRP747_p_1/) fails because of a non-atomic axiom in the input proof.

To reproduce:
```scala
  val p = Prover9Importer.lkProofFromFile(glob("**/GRP747+1/Prover9*.s.out").head)
  val Some(q) = CutIntroduction.compressLKProof(p, DeltaTableMethod(true), true)
  CERES(q)
```
(The non-atomic axioms come from the cut-introduced proof, since they are obtained from resolution refutations of the structural clausification of the solution conditions--and there we abbreviate subformulas because the cut-formula is large-ish.)

In this example, it would work to just expand the non-atomic axiom, but I guess in general CERES requires regular proofs?  If so, we should probably ensure that by calling `AtomicExpansion` and `regularize` in `CERES`.

cc @quicquid @shetzl

**Comment by quicquid** [comment]
For completeness, regularization  and eliminated definitions are necessary, but soundness is not affected. The reason I do not expand inside of CERES is that definition elimination is global (i.e. we need to pass the definition table) and affects skolemization. I wanted the user to decide on their own what to do, but i can make a call which factors these in.

Regarding non-atomic formulas in axioms: If we are talking about logical axioms, then atomic expansion is fine, but needs to be done after definition elimination(e.g. consider D = (forall x : P(x) -> Q(x)) ). When it comes to theory axioms, I'm not 100% sure how to proceed best.

In principle we can add the theory to the end-sequent and replace a theory axiom :- F(x) by 
                F(x) :- F(x)
------------------------------- all,l
(forall y : F(y)) :- F(x)

do axiom expansion and continue with normal CERES. I have the feeling that after that, we can delete the left hand thread from the end-sequent again. The reason is that in a projection, you either repeat some inference or skip it, but don't do anything else. Apart from contractions, no inferences work on the left hand occurrences of the theory axiom and since it is closed, we don't have any eigenvariable considerations. But that's just a sketch, not a real proof :-)

**Comment by gebner** [comment]
I agree with you that Skolemization and elimination of definitions should be done by the user.

I'm mainly concerned with non-atomic logical axioms, as these are generated by the resolution prover interface.  As for non-atomic theory axioms, I don't think we use them anywhere at the moment.
