### ISSUE TITLE
Weird context behavior

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#486]
This affects the mutablectx branch. I played around with contexts a bit and hit upon the following:

```
implicit var context =   FiniteContext()
context += Context.Sort("i")
context += hoc" P: t>o"
hof" ∀(x: t) P(x)"
```

This runs without issue, which I already don't understand. Why can I add a predicate constant of an undeclared type to the context and why can I parse formulas that contain said undeclared type? But it gets even weirder if you replace the last line with `fof" ∀(x: t) P(x)"`. Then you get `java.lang.IllegalArgumentException: Formula ∀x P(x:t) appears not to be a FOL formula. Parse it with hof.` Assuming that this correctly parses as a HOL formula, why does it not parse as a FOL formula? Am I overlooking something here?

**Comment by gebner** [comment]
> Why can I add a predicate constant of an undeclared type to the context
Oops, that's because I've accidentally removed a check for that--thanks for trying it out!

> why can I parse formulas that contain said undeclared type? 
Because types are not checked at the moment, also BabelSignature doesn't contain any information about defined types.  Adding such a check is low on my priority list--you can always create "invalid" formulas by using `#c('=' : t > i > s)` or just constructing them by hand.  The situation was different with the defined constants: there having fewer defined constants allows you to have more variables.

> Assuming that this correctly parses as a HOL formula, why does it not parse as a FOL formula?
Because HOL != FOL?  Or probably more helpfully: many-sorted FOL != FOL.  I'm not sure whether we should change this, personally I'm happy with HOLFormulas everywhere.

**Comment by loewenheim** [comment]
Ah, then I misunderstood what our FOL is. I thought it was many-sorted and that it only turned into HOL when you use variables over non-basic types.
