### ISSUE TITLE
autded.exercise3 and autded.exercise4 are broken

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#513]
The text printed to the student refers to TseitinPHP, etc. but these functions only exist in the object exercise3. In principle I would prefer the exercises to remain scripts but I realize that they are more difficult to maintain that way. On the other hand, having the student use autded.exercise3.TseitinPHP instead is also not ideal...

Ideally we could get rid of these setup-preambles altogether. TseitinPHP(n) can be written as TseitinCNF( Neg( PigeonHolePrinciple( n, n-1 ) ) ) which is easy to understand without further Scala knowledge. Can we have IsUnsat-methods taking clause sets for refutation-based provers like Prover9 or MiniSAT? This would be natural in the context of a course focussing on refutation-based provers and it would allow to get rid of these setup-preambles.

**Comment by gebner** [comment]
I have now added an `.isUnsat` method to Prover.  This means you can call `isUnsat` on everything from `PicoSAT` to `SPASS` to `LKProver` and it should work.

> `autded.exercise3.TseitinPHP`
In case you want to add an exercise in the future that requires helper functions again, you can also do the following:
```scala
import examples.autded.exercise3._

MiniSATIsUnsat(TseitinPHP(???))
```

Looking through these exercises, there is another problem:
```
scala> autded.exercise2

  Get the 5th Buss tautology by:
  gapt> BussTautology( 5 )

  Get the n-th pigeon hole principle tautology by:
  gapt> PigeonHolePrinciple( n, n-1 )

  Apply minisat to these by:
  gapt> MiniSAT.isValid( PigeonHolePrinciple( 5, 4 ))
  gapt> MiniSAT.isValid( BussTautology( 5 ))

  * What are (approximately) the largest n s.t. minisat finishes on the respective tautology within 5 seconds?

  * What are |φ_n| for these n?

res3: at.logic.gapt.examples.autded.exercise2.type = at.logic.gapt.examples.autded.exercise2$@77f08a21

scala> autded.exercise2
res4: at.logic.gapt.examples.autded.exercise2.type = at.logic.gapt.examples.autded.exercise2$@77f08a21
```

I.e., the text is only printed the first time.  It would be easy to fix this, by adding an apply method, and then invoking the exercises as `examples.autded.exercise2()` (note the parens).  However I'm not really convinced why these should be scala files anyway--since they are just text, shouldn't we store them as plain text files?

**Comment by shetzl** [comment]
I agree, converting to plain text makes sense. The only reason I used scala files in the beginning was that the user interface was not yet at a point suitable for this course and I had to provide some helper functions to make the exercises smoother.
