### ISSUE TITLE
Gaptic and incomplete proofs

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#520]
When Stefan and I visited Helmut Schwichtenberg, we compared notes about how the Fürstenberg proof is represented in GAPT and Minlog, respectively. Specifically in reference to the `insert` tactic, Prof. Schwichtenberg opined that it would be useful to be able to display proofs with "abbreviated" subproofs, eg:
```
 (π1)    (π2)
--------------
    Γ :- Δ
```

I've been wondering myself whether the behavior of Gaptic should be such that writing an incomplete proof does not throw an exception. I suppose in that case one would manually add `qed` to the end of the proof script to denote that this is actually a finished proof.

What do you think about this?

**Comment by gebner** [comment]
> display proofs with "abbreviated" subproofs

There are two possible approaches here:
1. The low hanging fruit is to toggle the visibility of subproofs in prooftool, i.e. click (or maybe ctrl-click, ...) on a sequent to show/hide the proof above it.
2. Add proof definitions inside LK.

I'm not sure how useful 1. is, but apparently there is already code in prooftool that should do just that (although it has some problems with dag proofs).

As for 2., I guess we could store defined proofs in `Context`.  But then we either have to modify most algorithms to add an extra `Context` argument (so that they can transparently proceed to the defined subproof), or eliminate proof definitions everywhere.  This seems to add a lot of common boilerplate for relatively little gain.
On the other hand, I can see a good use for the proof definitions inside `Context`: right now if you develop proofs using the tactics language and want to use a lemma you have just proved, you need to manually include it into the current proof.  If the list of lemmas were accessible, then tactics should as `rewrite` or `eql` could add the lemmas on-demand.

> writing an incomplete proof does not throw an exception

I do not like this concrete proposal, it makes it very easy to create unsound proofs.  All you have to do is forget `.qed` once, and you might be able to prove everything.

Is there a particular use case to support incomplete proofs?  I'm not opposed to the concept in general, I just believe it should come with suggestive names such as `IncompleteLemma`, `believeMe`, etc., that clearly indicate unsoundness.

**Comment by loewenheim** [comment]
Having proof definitions would be nice to have (in the technical sense of the phrase), but even being able to collapse subproofs in prooftool would be helpful.

As for incomplete proofs in the tactics language, I can definitely see the case for erring on the side of correctness. Doing the inverse, as you suggest, with a command that forces an incomplete proof would be completely acceptable to me.
