### ISSUE TITLE
LK: Better definition rules

### ISSUE THREAD

**Issue by loewenheim** [gapt/gapt#561]
Our current definition rules are a bit, shall we say … overly general. I would like to replace them with proper rules with the following interface:
```
DefinitionLeftRule(subProof: LKProof, aux: SequentIndex, definition: Definition, replacementContext: Abs)
```
`Definition` is a class that Gabriel has recently added to `Context`. Its interface is `Definition(what: Const, by: LambdaExpression)`. The `replacementContext` is a lambda term that describes where the defined symbol should be inserted. Example:
Let `d = Definition(<=, λxλy. ∃z x + z = y)`. Let `A = ∀x. 0 <= x`. Now consider the replacement context `ctx = λα. (∀x. α 0 x)`. Beta-reducing `ctx <=` would yield `A`, while beta-reducing `ctx λxλy. ∃z x + z = y` would yield the expanded formula.

There are a few questions to be answered, however.
- Should it be possible to introduce a definition in more than one place with a single rule application? I tend towards yes, since that is the current behavior of the equality rules.
- If we want a rule constructor that accepts the desired main formula instead of the context, which we probably do, and the answer to the previous question is "yes", then the constructor will have to determine the replacement context essentially by trial and error. Is this acceptable?
- How do definitions and definition rules interact with substitutions? Should definitions be substitutable?

**Comment by gebner** [comment]
> Should it be possible to introduce a definition in more than one place with a single rule application? I tend towards yes, since that is the current behavior of the equality rules.

Restricting unfolding to a single occurrence makes substitution (more) difficult. Think about the formula `X (<=)`: if you substitute `X` by `λx Y x x` then you have two occurrences of the defined constant.

> [...] rule constructor that accepts the desired main formula instead of the context, [...]

As you said, such a constructor could only work by some kind of heuristic, i.e. trial and error.  This heuristic would probably only work in first-order.

I'm not sure there is a big need for such a constructor.  AFAICT, the only places where we actually construct new definition rules are: tactics, ResolutionToLKProof, ExpansionProofToLK, and the LLK import.  The first three definitely have enough information to construct a replacement context.  That constructor would be primarily useful for LLK then.

I have now looked a bit more into LLK and the ntape proofs, and there seems to be a bigger problem than just the guessing of the replacement context.  There are definitions that do not define a constant by another term, but basically implement a rewriting system:
```
scala> nTape3.proofdb.Definitions.foreach(println)
[...]
(ite(ie(#v(i: i)), x, y),ie(#v(i: i)) * x + bm(1, ie(#v(i: i))) * y)
(ite(be(X:o), x, y),be(X:o) * x + bm(1, be(X)) * y)
```

Maybe a bit more readable:
```
ite(ie i, x, y) = ie i * x + bm(1, ie i) * y
ite(be X, x, y) = be X * x + bm(1, be X) * y
```

What do we do about them?  Such "definitions" might be useful for the prime proof as well (think `in x (set_1 y) = (x = y)`).

> How do definitions and definition rules interact with substitutions? Should definitions be substitutable?

Since definitions do not have free variables, I don't this is a problem.  Did you think of something different?

**Comment by gebner** [comment]
> ```
ite(ie i, x, y) = ie i * x + bm(1, ie i) * y
ite(be X, x, y) = be X * x + bm(1, be X) * y
```

Ok, looking at these two definitions again, they seem much less problematic--they are just special cases of the following general definition:
```
ite(u, x, y) = u * x + bm(1, u) * y
```

@quicquid Is there a reason why you used the two instances instead of the general definition?

**Comment by quicquid** [comment]
@gebner Perhaps I should explain the difference between the two conditionals first: The idea of both definitions is to encode the conditional in arithmetic with bounded subtraction (```bm```, I'll write - instead)..The difference between the two is the type of ```ie``` (individual encoding, ```i>i```) and ```be``` (boolean encoding, o>i).  Baiscally, if ```(ie i) = 0```, the expression evaluates to x, in case of ```(ie i) = 1```, it evaluates to y. The same should hold for (be X). For ```ie``` this is achieved by defining ```ie i``` as  ```1-(1-i)``` and for ```be X``` the definition is ```X -> be X = 0``` and ```-X -> be X = 1```.

The reason to do that was that during formalizing, I didn't know how well the lifting of the boolean expression to the term level would work out. An ugly alternative would be to reify each arithmetical predicate like ```<``` to the signature i>i>i (say as operator ```<<```) and write some lifting lemmas ```x < y <-> x << y = 1``` and ```-(x<y) <-> x << y = 0```. In the end, I didn't use the individual encoding, but it's still left in the axiom system.

**Comment by loewenheim** [comment]
@gebner 
> Restricting unfolding to a single occurrence makes substitution (more) difficult. Think about the formula X (<=): if you substitute X by λx Y x x then you have two occurrences of the defined constant.

I'm sorry, I don't follow.
> As you said, such a constructor could only work by some kind of heuristic, i.e. trial and error. This heuristic would probably only work in first-order.

What I mean here by "trial and error" is actually not so much a heuristic as trying all possibilities. You give the constructor the main formula you want to obtain and the definition you want to introduce. It then iterates over every subset of occurrences of the defined constant in the main formula, replaces that subset with the expanded definition and checks whether the result is the aux formula. Since at most one of these replacements can be correct, there is no guessing involved, just brute force.

An alternative would be to simply replace all occurrences of the defined constant. But your point that we might not actually even need this constructor is well taken.

> Since definitions do not have free variables, I don't this is a problem. Did you think of something different?

What I basically mean is, should the `Definition` class implement the `Substitutable` type class?

**Comment by quicquid** [comment]
Regarding the LLK definitions: you were right identifying them as a rewrite system. The idea is to interpret the equality ```D(x,y) = x + E(y)``` as directed. The requirements for this to work is 

* the definiendum is atomic
* that the free variables of the definiendum ```D(x,y)``` are a superset of the definiens ```x+E(y)```
* the rewrite system is strongly normalizing and terminating (i.e. definition via primitive and mutual recursion would be allowed)

I have a chapter in my thesis with the proof (with one small hole i still need to address) that these definitions are sound for standard LK with definitions (by removing definitions trough normalization modulo the rewrite system). What I implemented is stricter in the sense that LLK expects a semi-ordering of definitions with regard to containment i.e. recursive definitions are not allowed, but this is only a precondition which is checked before applying the rewriting.

The advantage of this definition is that it's closed under substitution and can be implemented in one pass over the whole proof. The way I wrote it, partial application is not allowed, but then to infer the substitution is just matching the unfolded definition against the possible instance. This brings me to the disadvantage, which is that the rewrite system is global to a proof, i.e. a definition rule depends on the full list of definitions. To decide the correct application of a definition inference, it should suffice to restrict the rewrite system to those rules which were used in the derivation tree above. But for non-iterative elimination, a full unfolding is necessary.

The questions for the definition checking @loewenheim is implementing, I'd be interested in would be the following:

* Would you like to unfold multiple definitions in one step? ( I'm not doing this in the n-Tape proof, but it's more common in interactive theorem proving, where the definition stays folded up in the lemma but the proof strategy and / or context contain knowledge about which definitions should be unfolded. At least for TLA, this technique of partial unfolding is pretty helpful since it reduces the workload of the backend trying to prove an obligation)

* Would you like to support recursive definitions? Then you have multiple rewrite rules for one defined symbol (e.g. ```D(0) = TRUE; D(s(x)) = D(x) /\ P(x, x+x) ```). If yes, then the next question is wether to support multiple parameters (e.g. 0-x = 0; x-0 = x; s(x) - s(y) = x - y ) and what to do in the case of more complex data-structures (the implicit assumption in the definition of D above was that for ```all x : x = 0 \/ exists y . x=s(y) ```)..

* How does the rule behave when a proof is constructed top-down (i.e. when the parent proof is not yet constructed)? Then you don't know the sub-system in your proof (yet).

**Comment by gebner** [comment]
>> Restricting unfolding to a single occurrence makes substitution (more) difficult. Think about the formula X (<=): if you substitute X by λx Y x x then you have two occurrences of the defined constant.

>I'm sorry, I don't follow.

If we restrict the definition rule to operate on a single occurrence, then we can do the following in one inference:
```
 X (λxλy ...)
-------------- def
   X (<=)
```
However this inference would need to be duplicated during substitution with `[X \ λx Y x x]`:
```
 Y (λxλy ...) (λxλy ...)
------------------------- def
  Y (<=) (λxλy  ...)
----------------------- def
    Y (<=) (<=)
```

> What I basically mean is, should the Definition class implement the Substitutable type class?

It could, but it would be the identity function, so I'm not sure if that's useful.

**Comment by gebner** [comment]
> Perhaps I should explain the difference between the two conditionals first: [...]

I'm still lost.  There is just *one* if-then-else that I can see: it has type `i>i>i`, and should do `ite(0, x, y) = y` and `ite(1, x, y) = x`.  This seems to be true no matter whether the condition is obtained by `be` or `ie`, right?

**Comment by gebner** [comment]
Regarding the LLK definitions:

> the definiendum is atomic

Just a nitpick, but we are defining functions here--do you consider function applications to be atomic?

> the rewrite system is strongly normalizing and terminating (i.e. definition via primitive and mutual recursion would be allowed)

Wouldn't you want to require confluence as well?

I'm beginning to like the rewriting definitions more and more, they would really help to make sense of the prime proof.  One thing I'm not sure about is how they interact with equality: if we have the definitions `P(a) →⊤ ` and `P(b) → ⊥`, how do you eliminate the definitions from the following proof?
```
------- top
:- ⊤
--------------- wk
a=b :- ⊤
-------------- def
a=b :- P(a)
--------------  eq
a=b :- P(b)
```

**Comment by gebner** [comment]
> The advantage of this definition is that it's closed under substitution and can be implemented in one pass over the whole proof.  The way I wrote it, partial application is not allowed, but then to infer the substitution is just matching the unfolded definition against the possible instance.

Hmm, there are some terms which are fully applied but cannot be definition-eliminated, e.g. `ite(x, y, z)`.  When we substitute this term, we can eliminate the definition using different rules.  Do you need to disallow such terms as well?

> This brings me to the disadvantage, which is that the rewrite system is global to a proof, i.e. a definition rule depends on the full list of definitions. To decide the correct application of a definition inference, it should suffice to restrict the rewrite system to those rules which were used in the derivation tree above. But for non-iterative elimination, a full unfolding is necessary.

I don't think the globality is a big problem.  We've always had global definition lists, and I don't think anybody wants to change that.

**Comment by gebner** [comment]
> How does the rule behave when a proof is constructed top-down (i.e. when the parent proof is not yet constructed)? Then you don't know the sub-system in your proof (yet).

At least the way I envision it, during top-down proof construction we only make sure that the proof is "structurally sound", i.e.: an and-right inference has the conjunction of the auxiliary formulas as main formula, eigenvariable conditions hold in strong quantifier rules, definition rules unfold a specified definition at a specific place, etc.  Basically everything that we can verify without looking at definitions, background theories, etc.

There are quite a few rules that require global assumptions--these would be checked after the construction of the complete proof.  (Actually you could subproofs as well at the moment, valid proofs only contain valid proofs as subproofs at the moment.)  There we can check that the definition rules use the correct definitions, theory axioms are the ones we specified, etc.

**Comment by quicquid** [comment]
> I'm still lost. There is just one if-then-else that I can see: it has type i>i>i, and should do ite(0, x, y) = y and ite(1, x, y) = x. This seems to be true no matter whether the condition is obtained by be or ie, right?

Yes, ie and be were just introduced to avoid creating two if-then-else symbols doing the same thing. In hindsight, it might have been better to use ite : o > i > i and define ie(0) = FALSE and ie(s(x)) = TRUE. The original motivation was to avoid axiomatizing the conditional, but in the end it didn't make much of a difference. The actual impact would come from replacing the axiomatization of  the ```<``` relation with an implementation in lambda calculus (which needs a primitive recursion operator).

**Comment by quicquid** [comment]
> Wouldn't you want to require confluence as well?

You are right, I always mix up notations - I need unique normal forms and termination (both confluent and terminating i.e. convergent). 

> I'm beginning to like the rewriting definitions more and more, they would really help to make sense of the prime proof. One thing I'm not sure about is how they interact with equality: if we have the definitions P(a) → ⊤ and P(b) → ⊥, how do you eliminate the definitions from the following proof?

My original proof was for LK without equality, but I should have a look at how to deal with it. In a way, the corresponding rewrite system would be:

    a <-> b
    P(a) -> ⊤
    P(b) -> ⊥

which destroys confluence. From an equational point of view we could reason that ```a=b => (P(a) <=> P(b)) => (⊤ <=> ⊥)``` and add this as an axiom replacing ```a=b```. In this case the two proofs

    ------------------- top
                        :- ⊤ 
    -------------------- weak,l
    (⊤ <=> ⊥) :-  ⊤ 
    =====================contr, and, impl l
    (⊤ <=> ⊥) :-   ⊥

That's ugly and works only for predicate definitions at best, though.

**Comment by gebner** [comment]
The TRS `{P(a) → ⊤, P(b) → ⊥}` is already convergent.  Is there any condition that I'm missing?  Why do you have to add `a → b` and `b → a`?

BTW, you can do the same proof without equational rules:
```
 ------ top
  :- ⊤
--------- def       ---------------ax
 :- P(a)              P(b) :- P(b)
------------------------------------ ⊃:l
       P(a) ⊃ P(b)  :- P(b)
   ---------------------------  ∀:l
     ∀X (X(a) ⊃ X(b)) :- P(b)
```

**Comment by quicquid** [comment]
I converted the equality ```a=b``` to a rewrite rule ( a -> b and b -> a) and added it to the system.

**Comment by loewenheim** [comment]
>>    What I basically mean is, should the Definition class implement the Substitutable type class?

>It could, but it would be the identity function, so I'm not sure if that's useful.

You're right, of course. That was me being thick.

**Comment by quicquid** [comment]
Just an update: I see the problem and wanted to make sure I hadn't made more errors. Unfortunately in my proof I require the definiendum to be of the form c(x1, ... xn) i.e. a constant applied to variables only. Then this situation doesn't appear, but also recursive definitions are pretty useless if the left hand side must be that general. I can recheck the proof and put it into a subdirectory of gapt as a start and will check how this can be properly generalized.

**Comment by gebner** [comment]
> EDIT: Alternative question—how should definitions interact with term replacement? In general it doesn't really work, since constants need not be replaced by constants.

Nothing really works in general when it comes to term replacements. :smile:  But I think we should apply the replacements to the definitions as well.  We do this in resolution proofs at the moment, where this is actually necessary.  Some external provers like to introduce definitions, and then we need to rename these new definitions so that they don't clash with constant symbols.

**Comment by gebner** [comment]
This seems to be implemented now.
