### ISSUE TITLE
help(ExpansionProof) redirects to 404 error within the help system

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#572]
Hello,

I just tried `help(ExpansionProof)` which redirects to [https://logic.at/gapt/api/#at.logic.gapt.proofs.expansion.ExpansionProof$](https://logic.at/gapt/api/#at.logic.gapt.proofs.expansion.ExpansionProof$) but apparently the help text for this object does not exist. Selecting ExpansionProof from the list on the left leads to [https://logic.at/gapt/api/#at.logic.gapt.proofs.expansion.ExpansionProof](https://logic.at/gapt/api/#at.logic.gapt.proofs.expansion.ExpansionProof) which is fine.

Might this be an older version of the documentation on the web?

**Comment by gebner** [comment]
> Might this be an older version of the documentation on the web?

Yes, there were indeed some troubles with the nightly documentation upload.  These are fixed now.

Unfortunately `help(ExpansionProof)` still does not work...

**Comment by loewenheim** [comment]
Fixed in 79af5c11f97c5e83f30a6e070eb7a4c91d8b165d. in fact, the `help` function is now smarter in general: If possible, it will open the documentation of classes as opposed to objects, which means that calling e.g. `help(Sequent)` will actually get you the page for the `Sequent` type and not the marginally useful companion object.
