### ISSUE TITLE
EProver / Prover9 cannot prove a propositional tautology

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#652]
Please consider the following propositional formula:

    gapt> val f = fof"a <-> (a <-> ⊤)"
    f: at.logic.gapt.expr.FOLFormula = (a ⊃ (a ⊃ ⊤) ∧ (⊤ ⊃ a)) ∧ ((a ⊃ ⊤) ∧ (⊤ ⊃ a) ⊃ a)

Both Prover9 and EProver fail to find a proof:

    gapt> EProver.getLKProof(f)
    res0: Option[at.logic.gapt.proofs.lk.LKProof] = None
    
    gapt> Prover9.getLKProof(f)
    res5: Option[at.logic.gapt.proofs.lk.LKProof] = None

Tested against rev 7e84db502867aa36f15fb5feb1c21260861bf0d9 but occurs already earlier (was in detached head state)

**Comment by gebner** [comment]
Can confirm.  Bug has already been present in 2.7.  Will fix ASAP.

**Comment by quicquid** [comment]
Thank you for the fast fix! I hadn't looked there at all...

**Comment by gebner** [comment]
Wow, thank you so much for finding this critical issue.  The problem was in the clausification procedure, where we skip clausification of sequents that are redundant.  For example `false :-` is redundant (because it is always true).  Here, we mistakenly identified sequents like `a -> true :-` as redundant too.

This bug has been present for one and a half years now, since the new clausification was first introduced.  I wonder why we never hit it in all this time.

**Comment by quicquid** [comment]
I'm not sure how many TPTP problems use top / bottom and hit exactly this case though - I'd assume this would result from some special cases of automatic translations, but otherwise it is rather exotic.
