### ISSUE TITLE
[dls-algorithm-for-formula-equations] simple example seems to fail with incorrect substitution

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#743]
Doing the following on the CLI
```
val g = hof"?X ( X(c) -> P(c) )"
val form = solveFormulaEquation( g ).get._2
val subst = solveFormulaEquation( g ).get._1
Escargot.isValid( BetaReduction.betaNormalize( subst( form )))
```
returns false. The Substitution returned by solveFormulaEquation replaces X by true which does not lead to a valid formula.

**Comment by fachammer** [comment]
I think this is related to the fact that we don't yet consider negative occurrences of X in the computation of a witness. Since this formula only has negative occurrences of X, it somehow implicitly returns true as a witness. I'll look into it.

**Comment by jvierling** [comment]
A similar problem arises when trying to solve the following instance obtained from a schematic extended herbrand sequent:
```
∃X_0
  ∃X_1
  ((X_0(x_1) → X_0(x_2) ∧ X_0(s(s(x_2)))) ∧
      (X_1(x_2) → X_1(0) ∧ X_1(s(s(s(s(0)))))) ∧
      P(0) ∧
      (P(x_1) → P(s(x_1))) ∧
      (P(s(x_1)) → P(s(s(x_1)))) →
    P(s(s(s(s(s(s(s(s(0))))))))))
```
For this instance the algorithm returns the invalid solution
```
(Substitution(X_0:i>o -> λx_0_0 ⊤, X_1:i>o -> λx_1_0 ⊤),(X_0(x_1) → X_0(x_2) ∧ X_0(s(s(x_2)))) ∧
    (⊤ → ⊤ ∧ ⊤) ∧
    P(0) ∧
    (P(x_1) → P(s(x_1))) ∧
    (P(s(x_1)) → P(s(s(x_1)))) →
  P(s(s(s(s(s(s(s(s(0))))))))))
```

**Comment by fachammer** [comment]
@shetzl The current commit should fix the issue with your example. It still produces only the witness according to the positive occurrences, but that should work anyway. I'm now working on implementing the witness based on the negative occurrences.

@jvierling regarding your example: now the code doesn't produce an invalid witness, but instead fails because positive and negative occurrences of `X_0` cannot be separated after substituting the witness for `X_1` because then there are nested conjunctions and disjunctions as far as I can see from debugging it a little. According to the description of the DLS algorithm, the distribution of conjunctions over disjunctions only occurs on the top level and does not go deeper. However, in this example producing a DNF would work and the algorithm could proceed. 

How should we go on from here? I wonder, whether it would work to first put the first order formula into prenex normal form, then produce a DNF of the quantifier-free part, then move the universal quantifiers down and proceed from there. Any ideas?

**Comment by jvierling** [comment]
@fachammer 
> I wonder, whether it would work to first put the first order formula into prenex normal form, then produce a DNF of the quantifier-free part, then move the universal quantifiers down and proceed from there. 

This sounds reasonable to me. I think the original formulation of the algorithm distributes only the outermost conjunctions over disjunctions in order to avoid an exponential blowup of the size of the formula. In order to increase the size of the formula as little as possible it should suffice to transform subformulas whose occurrences of `X` cannot be separated.
As far as I can tell the implementation described in [1] uses a similar technique to separated the occurrences of `X`.
We can discuss this in more detail during the meeting.

[1] Gustafsson, Joakim. "An implementation and optimization of an algorithm for reducing formulae in second-order logic."

**Comment by shetzl** [comment]
The algorithm now returns a correct solution for the original example.
