### ISSUE TITLE
"xor" does not behave as other function names in first order formula interpolation

### ISSUE THREAD

**Issue by marisgg** [gapt/gapt#762]
Hello!

Thank you for _gapt_ and the effort you put into its module and documentation.

I have a simple question. Why does `fof"xor(x)"` behave differently to other function names in first-order formula interpolation?

The following exception occurs, which I did not expect:
```scala
scala> fof"or(x)"
res26: gapt.expr.formula.fol.FOLFormula = or(x): o

scala> fof"xor(x)"
java.lang.IllegalArgumentException: Formula xor(x): o appears not to be a FOL formula. Parse it with hof.
  at gapt.expr.util.ExpressionParseHelper.fof(ExpressionParseHelper.scala:168)
  ... 26 elided
```

See the following example:

```scala
scala> val x = FOLVar("x")
x: gapt.expr.formula.fol.FOLVar = x

scala> FOLFunction("f",x)
res23: gapt.expr.formula.fol.FOLTerm = f(x)

scala> FOLFunction("xor",x)
res24: gapt.expr.formula.fol.FOLTerm = #c(xor: i>i)(x): i

scala> FOLFunction("or",x)
res25: gapt.expr.formula.fol.FOLTerm = or(x)
```

It seems that 'xor' has some underlying meaning here, contrarily to any other function name, even though 'xor' is never defined in the lifetime of the _gapt_ shell. Excuse me if I'm missing something here, I might very well be.

**Comment by jvierling** [comment]
GAPT has constants for some connectives only (equality, bottom, top, negation, conjunction, disjunction, and the quantifiers). Other formulas have to be expressed in terms of these connectives. Hence, when you run `fof"xor(x)"` GAPT does not know `xor` and can therefore not parse a first-order formula. However, GAPT has some abbreviations for equivalence (infix `<->`) and negated equality (infix `!=`). 

When you run `FOLFunction("xor",x)`, GAPT interprets `xor` as a function symbol of sort `i>i`. The expressions `FOLFunction("f",x)` and `FOLFunction("or",x)` work similarly by interpreting 'f' and 'or' as constants of sort `i>i`. The output is different in the case of "xor" because constants usually do not start with the letter "x".
